import {test,expect} from '@playwright/test';
import {library} from './library-fixture.js';
test('crear con QR temporal, recibir portada y editar con autoguardado',async({page})=>{
 const state=await library(page);await page.getByRole('button',{name:'+ Agregar libro',exact:true}).click();
 const modal=page.locator('#library-modal');await modal.locator('[name=titulo]').fill('Libro nuevo');await modal.locator('[name=autor]').fill('Nombre original');await modal.getByRole('button',{name:/Manejar portada e imágenes/}).click();await expect(modal.locator('.lib-draft-qr img')).toBeVisible();await expect(modal.getByRole('dialog',{name:'Manejo de portada'})).toBeVisible();expect(await page.evaluate(()=>getComputedStyle(document.documentElement).overflowY)).toBe('hidden');
 state.drafts[0].uploaded_at=new Date().toISOString();await expect(modal.getByText('Portada recibida. Guardá el libro para conservarla.')).toBeVisible({timeout:12000});
 await modal.getByRole('button',{name:'Cerrar portada',exact:true}).click();await modal.getByRole('button',{name:'Agregar libro',exact:true}).click();await expect(modal.getByRole('heading',{name:'Libro nuevo',exact:true})).toBeVisible();expect(state.books).toHaveLength(2);expect(state.books[1].portada).toContain('/books/draft-');expect(state.drafts).toHaveLength(0);
 await modal.getByRole('button',{name:'✏️ Editar',exact:true}).click();const editor=modal.locator('.library-inline-editor');await editor.locator('[name=autor]').fill('Nombre corregido');await editor.locator('[name=titulo]').click();await expect(editor.locator('.lib-autosave-status')).toHaveText('Guardado ✓');expect(state.books[1].autor).toBe('Nombre corregido');
 await editor.getByRole('button',{name:'🔎 Buscar sinopsis en Google',exact:true}).click();await editor.getByRole('button',{name:'Usar esta sinopsis'}).click();await expect(editor.locator('.lib-autosave-status')).toHaveText('Guardado ✓');expect(state.books[1].descripcion).toBe('Sinopsis de prueba');
});
test('lectura visible permite fechas anteriores y diez estrellas',async({page})=>{
 const state=await library(page,{fixture:{books:[{id:1,titulo:'Libro de prueba',autor:'Autora',lista:'catalogo',estado_lectura:'leyendo',paginas:120,pagina_actual:10,fecha_inicio:'2020-01-01'}]}});
 await page.locator('.lib-nav [data-view=lecturas]').click();const form=page.locator('[data-transition=finish]');await form.locator('[name=start]').fill('2020-01-01');await form.locator('[name=end]').fill('2020-01-03');await form.getByRole('button',{name:'9 de 10',exact:true}).click();await form.getByRole('button',{name:'✅ Concluí'}).click();await expect.poll(()=>state.transitions.length).toBe(1);expect(state.transitions[0].p_data).toMatchObject({start:'2020-01-01',end:'2020-01-03',rating:'9'});
});
test('lector no recibe editor ni botón para crear',async({page})=>{await library(page,{writer:false});await expect(page.getByRole('button',{name:'+ Agregar libro',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Ver ficha de Libro de prueba'}).first().click();await expect(page.locator('.library-inline-editor')).toHaveCount(0);});
