import fs from 'node:fs';
const exact=(src,from,to,label)=>{const n=src.split(from).length-1;if(n!==1)throw new Error(`${label}: ${n} coincidencias`);return src.replace(from,to);};

let main=fs.readFileSync('src/main.js','utf8');
main=exact(main,"import { daySummary, dayWelcome } from './daily.js';","import {dayWelcome} from './daily.js';",'daily import');
main=exact(main,"import {dayDetailData} from './day-detail-data.js';\nimport {calendarDayIndicators,compactLiters} from './calendar-day-indicators.js';","import {daySnapshot} from './day-service.js';\nimport {currentRoute,navigateRoute,ensureRoute,onRouteChange} from './router.js';\nimport {APP_NAV,mobileNavigation,viewLabel} from './app-navigation.js';\nimport {calendarDayIndicators,compactLiters} from './calendar-day-indicators.js';",'service router imports');
main=exact(main,"let user=null,view='today',areaFilter='',date=dayKey(),month=date.slice(0,7),tab='tareas',search='',authMode='login',recovery=false,ready=false,toastTimer;","const initialRoute=currentRoute();\nlet user=null,view=initialRoute.view,areaFilter=initialRoute.areaId||'',date=dayKey(),month=date.slice(0,7),tab='tareas',search='',authMode='login',recovery=false,ready=false,toastTimer;",'route initial state');
main=exact(main,"const nav=[['today','LayoutDashboard','Mi día'],['calendar','CalendarDays','Calendario'],['areas','Layers','Mis áreas'],['progress','ChartNoAxesColumn','Progreso'],['diary','NotebookPen','Mi diario'],['library','LibraryBig','Biblioteca'],['space','CheckCheck','Tareas']];const mobileNav=nav.filter(([id])=>['today','calendar','library','space'].includes(id));","const nav=APP_NAV,mobileNav=mobileNavigation();",'navigation config');
main=exact(main,"${nav.find(n=>n[0]===view)?.[2]||'Mi día'}","${viewLabel(view)}",'breadcrumb label');
main=exact(main,"document.addEventListener('habits:rerender',()=>render());","document.addEventListener('habits:rerender',()=>render());\nonRouteChange(route=>{view=route.view;areaFilter=route.view==='areas'?(route.areaId||''):'';if(user&&ready)render();});\nensureRoute();",'route listener');

const todayOld="function todayDashboardView(){const today=dayKey(),hs=rec('habit').sort((a,b)=>(a.order||0)-(b.order||0)),logs=rec('log'),name=settings().name||user.user_metadata?.name||'';const dayMode=effectiveDayMode(settings(),today);const done=effectiveHabitsForDate(hs,today,dayMode).filter(h=>habitStatus(h,logs,today).done);const summary=daySummary({habits:hs,logs,events:rec('event'),eventLogs:rec('eventLog'),readings:rec('reading'),journals:rec('journal'),finishedBooks:catalog().finishedToday},today,dayMode);const upcoming=rec('event').filter(e=>occurs(e,today)).sort((a,b)=>(a.time||'').localeCompare(b.time||''));const completedLogs=logs.filter(l=>l.date===today&&l.status==='done');const reads=rec('reading').filter(r=>r.date===today);const baseShown=effectiveHabitsForDate(hs,today,dayMode),todayUi=todayUiContext({events:rec('event'),habits:baseShown,dayMode,escape:esc}),shown=todayUi.habits;const visibleStats=dayStats(hs,logs,today,dayMode);return `";
const todayNew="function todayDashboardView(){const today=dayKey(),logs=rec('log'),name=settings().name||user.user_metadata?.name||'',day=daySnapshot({date:today,records:rec,settings:settings(),finishedBooks:catalog().finishedToday}),dayMode=day.mode,done=day.habitRows.filter(({status})=>status.done),summary=day.summary,upcoming=day.events,completedLogs=logs.filter(l=>l.date===today&&l.status==='done'),reads=day.detail.readings,baseShown=day.effectiveHabits,todayUi=todayUiContext({events:rec('event'),habits:baseShown,dayMode,escape:esc}),shown=todayUi.habits,visibleStats=day.stats;return `";
main=exact(main,todayOld,todayNew,'today snapshot');

const detailOld=`function dayDetailView(d){\n const events=rec('event').filter(e=>occurs(e,d)).sort((a,b)=>(a.time||'').localeCompare(b.time||''));\n const mode=effectiveDayMode(settings(),d),habits=effectiveHabitsForDate(rec('habit'),d,mode);\n const rows=habits.map(h=>({h,status:habitStatus(h,rec('log'),d)})),done=rows.filter(({status})=>status.done).length;\n const day=dayDetailData({date:d,journals:rec('journal'),photos:rec('photo'),dailyPlans:rec('dailyPlan'),tasks:rec('task'),readings:rec('reading'),logs:rec('log'),meals:rec('meal')});`;
const detailNew=`function dayDetailView(d){\n const snapshot=daySnapshot({date:d,records:rec,settings:settings()}),events=snapshot.events,mode=snapshot.mode;\n const rows=snapshot.habitRows.map(({habit,status})=>({h:habit,status})),done=rows.filter(({status})=>status.done).length;\n const day=snapshot.detail;`;
main=exact(main,detailOld,detailNew,'day detail snapshot');

main=exact(main,"weekStats=week.map(d=>dayStats(rec('habit'),logs,d,effectiveDayMode(settings(),d)))","weekStats=week.map(d=>daySnapshot({date:d,records:rec,settings:settings()}).stats)",'progress week stats');
main=exact(main,"const st=dayStats(rec('habit'),logs,d,effectiveDayMode(settings(),d));return `<div><b>${st.done}</b>","const st=daySnapshot({date:d,records:rec,settings:settings()}).stats;return `<div><b>${st.done}</b>",'progress week chart');
main=exact(main,"const d=addDays(today,i-27),st=dayStats(rec('habit'),logs,d);return `<button","const d=addDays(today,i-27),st=daySnapshot({date:d,records:rec,settings:settings()}).stats;return `<button",'progress heatmap');

const navigationOld="if(a==='nav'){view=el.dataset.view;modal.dataset.dirty='false';modal.close();render();window.scrollTo(0,0);return;}if(a==='area'){view='areas';areaFilter=id||'';render();return;}if(a==='space-tab'){tab=el.dataset.tab;render();return;}if(a==='progress'){view='progress';render();return;}if(a==='library-book'){window.libraryQuery='';window.libraryBookId=el.dataset.id||'';view='library';modal.close();render();return;}if(a==='library'){view='library';modal.close();render();return;}";
const navigationNew="if(a==='nav'){modal.dataset.dirty='false';modal.close();navigateRoute({view:el.dataset.view});window.scrollTo(0,0);return;}if(a==='area'){navigateRoute({view:'areas',areaId:id||''});return;}if(a==='space-tab'){tab=el.dataset.tab;render();return;}if(a==='progress'){navigateRoute({view:'progress'});return;}if(a==='library-book'){window.libraryQuery='';window.libraryBookId=el.dataset.id||'';modal.close();navigateRoute({view:'library'});return;}if(a==='library'){modal.close();navigateRoute({view:'library'});return;}";
main=exact(main,navigationOld,navigationNew,'routed actions');
main=exact(main,"if(a==='date'){const fromCalendar=view==='calendar';date=d;month=d.slice(0,7);view='calendar';render();if(fromCalendar&&window.matchMedia('(max-width:900px)').matches)","if(a==='date'){const fromCalendar=view==='calendar';date=d;month=d.slice(0,7);navigateRoute({view:'calendar'});if(fromCalendar&&window.matchMedia('(max-width:900px)').matches)",'date route');
fs.writeFileSync('src/main.js',main);
