from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
main=ROOT/'src/main.js'
s=main.read_text()

def one(old,new,label):
    global s
    if old not in s:
        raise SystemExit(f'No encontré patrón: {label}')
    s=s.replace(old,new,1)

one("import './style.css';", "import './style.css';\nimport './accessibility.css';", 'accessibility import')
one("import {AREAS,ICONS,PALETTE,uid,dayKey,parseDay,addDays,scheduled,occurs,dayStats,streak,elapsed,fmtDuration,weekKeys,eventOnDate} from './domain.js';",
    "import {AREAS,ICONS,PALETTE,uid,dayKey,parseDay,addDays,scheduled,occurs,dayStats,streak,elapsed,fmtDuration,weekKeys,eventOnDate,flexibleWeekly,weeklyProgress,habitStatus} from './domain.js';", 'domain imports')
one("import {notificationsView,notificationsAction} from './notifications.js';",
    "import {notificationsView,notificationsAction} from './notifications.js';\nimport {diaryEntries,personalProjects,laterTasks,isDiaryEntry,isHydrationHabit,dayModeAllowsHabit} from './selectors.js';\nimport {findEventConflicts,conflictMessage} from './schedule-conflicts.js';\nimport {waterStats} from './hydration.js';", 'new imports')

old="function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),4200);}"
new="function toast(message,undo=null){const el=document.querySelector('#toast');el.replaceChildren(document.createTextNode(message));if(undo){const b=document.createElement('button');b.type='button';b.className='toast-undo';b.textContent='Deshacer';b.onclick=()=>{undo();el.classList.remove('visible');};el.append(b);}el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),5200);}"
one(old,new,'toast undo')

old="const nav=[['today','LayoutDashboard','Mi día'],['calendar','CalendarDays','Calendario'],['areas','Layers','Mis áreas'],['space','Flower2','Mi espacio'],['diary','NotebookPen','Mi diario']];app.innerHTML=`"
new="const nav=[['today','LayoutDashboard','Mi día'],['calendar','CalendarDays','Calendario'],['areas','Layers','Mis áreas'],['progress','ChartNoAxesColumn','Progreso'],['diary','NotebookPen','Mi diario'],['space','Flower2','Más']];const mobileNav=nav.filter(([id])=>['today','calendar','areas','progress','space'].includes(id));app.innerHTML=`"
one(old,new,'navigation model')
one('<div class="breadcrumb">Mi espacio <span>/</span> <strong>', '<div class="breadcrumb">Habits <span>/</span> <strong>', 'breadcrumb')
one("${view==='today'?todayView():view==='calendar'?calendarView():view==='areas'?areasView():view==='diary'?journalView():spaceView()}", "${view==='today'?todayView():view==='calendar'?calendarView():view==='areas'?areasView():view==='progress'?progressView():view==='diary'?journalView():spaceView()}", 'view dispatch')
one('<nav class="mobile-nav">${nav.map', '<nav class="mobile-nav">${mobileNav.map', 'mobile nav')

one("const done=hs.filter(h=>logs.some(l=>l.habitId===h.id&&l.date===today&&l.status==='done'));", "const done=hs.filter(h=>habitStatus(h,logs,today).done);", 'today done')
one("const dayMode=effectiveDayMode(settings());const shown=hs.filter(h=>scheduled(h,today)&&(dayMode==='tranquilo'?h.essential:true));", "const dayMode=effectiveDayMode(settings());const shown=hs.filter(h=>scheduled(h,today)&&dayModeAllowsHabit(h,dayMode));const visibleStats=dayStats(shown,logs,today);", 'day mode behavior')
one("${done.length?'Mirá todo lo que ya hiciste.':'Un nuevo día.<br>Un poquito más para vos.'}", "${esc(dayWelcome().hero)}", 'hero by time')
one("${icon('Sparkles')}${done.length?'¡Bien por vos! Cada paso suma.':'Sin apuro. Lo importante es empezar.'}", "${icon('Sparkles')}${esc(dayWelcome().note)}", 'hero note')
one("--progress:${stats.percent*3.6}deg", "--progress:${visibleStats.percent*3.6}deg", 'visible progress css')
one("${stats.done}<small> / ${stats.total}</small>", "${visibleStats.done}<small> / ${visibleStats.total}</small>", 'visible progress count')
one("${stats.percent}% de tu día", "${visibleStats.percent}% de tu día", 'visible progress percent')

s=re.sub(r"function habitCard\(h,d\)\{.*?\nfunction eventCard", '''function habitCard(h,d){const st=habitStatus(h,rec('log'),d),a=area(h.area),done=st.done,skip=st.skip;let metric='';if(st.hydration){metric=`${icon('Droplets')}${(st.value/1000).toLocaleString('es-PY')} / ${(st.target/1000).toLocaleString('es-PY')} L`;}else if(flexibleWeekly(h)){metric=`${icon('Target')}${st.weekly.done} / ${st.weekly.target} esta semana${done?' · hecho hoy':st.weekly.complete?' · meta cumplida':''}`;}else metric=h.type==='check'?`${icon('Sun')}${esc(h.period)}`:`${icon(h.type==='time'?'Clock':'Target')}${st.value||0} / ${h.target} ${esc(h.unit)}`;const action=st.hydration?'water-custom':'habit-action',label=st.hydration?'Sumar agua':done?'Hecho':skip?'Retomar':h.type==='check'?'Marcar hecho':'Registrar';return `<article draggable="true" data-habit-id="${h.id}" class="habit-card ${done?'done':''} ${skip?'skipped':''}" style="--area:${safeColor(h.color||a.color)}"><div class="habit-top"><span class="habit-icon">${icon(h.icon)}</span><div class="touch-order">${btn(icon('ChevronLeft'),'habit-move',`data-id="${h.id}" data-dir="-1" aria-label="Mover ${esc(h.name)} antes"`,'icon-button')}${btn(icon('ChevronRight'),'habit-move',`data-id="${h.id}" data-dir="1" aria-label="Mover ${esc(h.name)} después"`,'icon-button')}</div>${btn(icon('MoreHorizontal'),'edit-habit',`data-id="${h.id}" aria-label="Editar ${esc(h.name)}"`,'icon-button')}</div><span class="habit-area">${esc(a.name)}</span><h3>${esc(h.name)}</h3><p>${metric}</p><div class="habit-bottom">${btn(icon(done?'CheckCheck':skip?'RotateCcw':st.hydration?'Droplets':h.type==='check'?'Check':'Plus')+label,action,st.hydration?'':`data-id="${h.id}" data-date="${d}"`,'habit-check')}${done&&!st.hydration&&st.log?.at?`<span class="done-time">${time(st.log.at)}</span>`:!st.hydration?btn('Hoy no','skip',`data-id="${h.id}" data-date="${d}"`,'text-button small'):''}</div></article>`;}
function eventCard''', s, count=1, flags=re.S)
if 'function habitCard(h,d){const st=habitStatus' not in s: raise SystemExit('No pude reemplazar habitCard')

s=re.sub(r"function spaceView\(\)\{.*?\nfunction taskList", '''function spaceView(){const tabs=[['tareas','Pendientes'],['later','Para después'],['biblioteca','Biblioteca'],['proyectos','Proyectos'],['planning','Estudio y trabajo']];return `${heading('ORGANIZÁ SIN PERDERTE','Más','Pendientes, proyectos, estudio y biblioteca en un solo lugar.')}<div class="chips space-tabs">${tabs.map(([id,name])=>btn(name,'space-tab',`data-tab="${id}"`,tab===id?'chip selected':'chip')).join('')}</div>${tab==='planning'?planningView({esc,btn}):tab==='biblioteca'?libraryView():tab==='proyectos'?projectsView():tab==='later'?`<div class="section-title"><div><h2>Para después</h2><p>Ideas y pendientes sin fecha, guardados sin presión.</p></div>${btn(icon('Plus')+'Nueva tarea','new-task','','button primary')}</div>${taskList(laterTasks(rec('task')))}`:`<div class="section-title"><h2>Una cosa a la vez</h2>${btn(icon('Plus')+'Nueva tarea','new-task','','button primary')}</div>${taskList(rec('task'))}`}`;}
function taskList''', s, count=1, flags=re.S)
if "['later','Para después']" not in s: raise SystemExit('No pude reemplazar spaceView')

s=re.sub(r"function journalView\(\)\{.*?\nfunction projectsView", '''function journalView(){const entries=diaryEntries(rec('journal')),j=entries.find(j=>j.date===dayKey());return `<section class="journal-intro"><div><p class="eyebrow">UN MOMENTO CON VOS</p><h2>¿Qué te gustaría recordar de hoy?</h2><p>Un pensamiento, una alegría, algo que aprendiste.</p>${btn(icon('NotebookPen')+(j?'Editar mi día':'Escribir sobre mi día'),'journal','','button primary')}</div><span class="journal-flower">${icon('Flower2')}</span></section><div class="journal-grid">${entries.sort((a,b)=>b.date.localeCompare(a.date)).map(j=>`<button class="journal-card" data-action="edit-journal" data-id="${j.id}"><small>${prettyDate(j.date)}</small><h3>${['','😔','😐','🙂','😊','🤩'][j.mood||0]||'Mi día'}</h3><p>${esc(j.text||'Hoy me tomé un momento para registrar cómo me sentía.')}</p></button>`).join('')||empty('Este espacio es tuyo. No hace falta escribir algo perfecto.')}</div>`;}
function projectsView''', s, count=1, flags=re.S)
one("${rec('project').filter(p=>p.category!=='subject').map", "${personalProjects(rec('project')).map", 'personal projects selector')

s=re.sub(r"function progressView\(\)\{.*?\nfunction showModal", '''function progressView(){const today=dayKey(),week=weekKeys(today),logs=rec('log'),doneLogs=logs.filter(l=>week.includes(l.date)&&l.status==='done'),minutes=rec('reading').filter(r=>week.includes(r.date)).reduce((n,r)=>n+Number(r.minutes),0),c=catalog(),finishedBooks=c.allowed?(c.finishedCount||0):rec('book').filter(b=>b.status==='finished').length,water=waterStats(logs,today,7);return `<div class="section-title"><div><h2>Mi progreso</h2><p>Tu semana, tus constancias y tus logros.</p></div>${btn('Ver resumen semanal','extra-week','','button outline')}</div><div class="stat-grid with-water"><article class="panel"><span>${icon('CheckCheck')} ESTA SEMANA</span><strong>${doneLogs.length}</strong><p>hábitos completados</p></article><article class="panel"><span>${icon('BookOpen')} TIEMPO PARA LEER</span><strong>${minutes}<small> min</small></strong><p>de lectura registrada esta semana</p></article><article class="panel"><span>${icon('Target')} TUS LIBROS</span><strong>${finishedBooks}</strong><p>historias terminadas</p></article><article class="panel water-progress-stat"><span>💧 PROMEDIO DE AGUA</span><strong>${water.average.toLocaleString('es-PY')}<small> L/día</small></strong><p>${water.total.toLocaleString('es-PY')} L en 7 días · ${water.daysWithWater}/7 días con registro</p></article></div><section class="panel"><div class="section-title"><h2>Tu semana, paso a paso</h2><p>Hábitos completados</p></div><div class="week-chart">${week.map(d=>{const st=dayStats(rec('habit'),logs,d);return `<div><b>${st.done}</b><div class="bar-track"><span style="height:${st.percent}%"></span></div><small>${prettyDate(d,{weekday:'short'})}</small></div>`;}).join('')}</div></section><section class="panel"><h2>Pequeñas constancias</h2><p class="muted">Las pausas registradas y los días no programados no cortan tu racha.</p>${rec('habit').filter(h=>!h.archived).map(h=>`<div class="streak-row">${icon(h.icon)}<span>${esc(h.name)}</span><b>${streak(h,logs,today)} ${flexibleWeekly(h)?'semanas':'días'}</b></div>`).join('')}</section><section class="panel water-progress-detail"><h2>Tu agua, día por día</h2><p class="muted">Promedio de los últimos 7 días, contando también los días sin registro.</p><div class="water-days">${water.keys.map((d,i)=>`<div class="water-day"><b>${water.liters[i].toLocaleString('es-PY')} L</b><small>${prettyDate(d,{weekday:'short'})}</small></div>`).join('')}</div></section><section class="panel"><h2>Las últimas cuatro semanas</h2><div class="heatmap">${Array.from({length:28},(_,i)=>{const d=addDays(today,i-27),st=dayStats(rec('habit'),logs,d);return `<button style="--level:${st.percent/100}" data-action="date" data-date="${d}" title="${d}: ${st.done} completados"><small>${parseDay(d).getDate()}</small></button>`;}).join('')}</div></section>`;}
function showModal''', s, count=1, flags=re.S)
if 'PROMEDIO DE AGUA' not in s: raise SystemExit('No pude reemplazar progressView')

old="function showModal(title,body,onSubmit){modal.innerHTML=`<div class=\"modal-heading\"><h2>${title}</h2>${btn(icon('X'),'close','aria-label=\"Cerrar\"','icon-button')}</div>${body}`;if(!modal.open)modal.showModal();paintIcons();const f=modal.querySelector('form');if(f)f.onsubmit=async e=>{e.preventDefault();const submit=f.querySelector('[type=\"submit\"]');if(submit)submit.disabled=true;try{await onSubmit(new FormData(f));}catch(error){toast('No se pudo guardar: '+error.message);}finally{if(submit)submit.disabled=false;}};}"
new="function showModal(title,body,onSubmit){modal.dataset.dirty='false';modal.innerHTML=`<div class=\"modal-heading\"><h2>${title}</h2>${btn(icon('X'),'close','aria-label=\"Cerrar\"','icon-button')}</div>${body}`;if(!modal.open)modal.showModal();paintIcons();const f=modal.querySelector('form');if(f){f.addEventListener('input',()=>modal.dataset.dirty='true');f.addEventListener('change',()=>modal.dataset.dirty='true');f.onsubmit=async e=>{e.preventDefault();const submit=f.querySelector('[type=\"submit\"]');if(submit)submit.disabled=true;try{await onSubmit(new FormData(f));modal.dataset.dirty='false';}catch(error){toast('No se pudo guardar: '+error.message);}finally{if(submit)submit.disabled=false;}};}modal.oncancel=e=>{if(modal.dataset.dirty==='true'){e.preventDefault();if(confirm('Tenés cambios sin guardar. ¿Descartarlos?')){modal.dataset.dirty='false';modal.close();}}};}\nfunction closeModalSafely(){if(modal.dataset.dirty==='true'&&!confirm('Tenés cambios sin guardar. ¿Descartarlos?'))return false;modal.dataset.dirty='false';modal.close();return true;}"
one(old,new,'dirty forms')

one("${select('Proyecto','projectId',[['','Sin proyecto'],...rec('project').map(p=>[p.id,p.name])],r.projectId||'')}", "${select('Proyecto','projectId',[['','Sin proyecto'],...personalProjects(rec('project')).map(p=>[p.id,p.name])],r.projectId||'')}", 'project dropdown')

old="if(kind==='event'){if(data.end&&!data.time)throw new Error('Indicá una hora inicial.');if(data.end&&data.end<=data.time)throw new Error('La hora final debe ser posterior a la inicial.');if(data.until&&data.until<data.date)throw new Error('La fecha final no puede ser anterior al inicio.');const overlap=rec('event').some(e=>e.id!==id&&occurs(e,data.date)&&e.time&&data.time&&data.time<(e.end||e.time)&&e.time<(data.end||data.time));if(overlap)warning='Guardado, pero coincide con otro evento de ese día. Revisá el calendario.';}"
new="if(kind==='event'){if(data.end&&!data.time)throw new Error('Indicá una hora inicial.');if(data.end&&data.end<=data.time)throw new Error('La hora final debe ser posterior a la inicial.');if(data.until&&data.until<data.date)throw new Error('La fecha final no puede ser anterior al inicio.');const conflicts=findEventConflicts(data,rec('event'),{ignoreId:id,days:180});if(conflicts.length&&!confirm(conflictMessage(conflicts)+' ¿Querés guardar igualmente?'))return;}"
one(old,new,'event conflicts')

one("if(a==='close'){modal.close();return;}", "if(a==='close'){closeModalSafely();return;}", 'safe close')
one("if(a==='nav'){view=el.dataset.view;modal.close();render();window.scrollTo(0,0);return;}", "if(a==='nav'){view=el.dataset.view;modal.dataset.dirty='false';modal.close();render();window.scrollTo(0,0);return;}", 'nav close')
one("if(a==='progress'||a==='library'){view='space';tab=a==='progress'?'progreso':'biblioteca';render();return;}", "if(a==='progress'){view='progress';render();return;}if(a==='library'){view='space';tab='biblioteca';render();return;}", 'progress route')
one("if(a==='habit-action'){habitAction(id,d);return;}", "if(a==='habit-move'){const hs=rec('habit').sort((x,y)=>(x.order||0)-(y.order||0)),from=hs.findIndex(h=>h.id===id),to=Math.max(0,Math.min(hs.length-1,from+Number(el.dataset.dir||0)));if(from>=0&&from!==to){hs.splice(to,0,hs.splice(from,1)[0]);hs.forEach((h,i)=>{if(h.order!==i)db.put('habit',{...h,order:i},h.id);});}return;}if(a==='habit-action'){habitAction(id,d);return;}", 'touch reorder')
one("db.put('log',{habitId:id,date:d,status:'skip',at:new Date().toISOString(),value:0},`log:${id}:${d}`);toast('Pausa registrada. Descansar también cuenta.');", "const skipId=`log:${id}:${d}`;db.put('log',{habitId:id,date:d,status:'skip',at:new Date().toISOString(),value:0},skipId);toast('Pausa registrada. Descansar también cuenta.',()=>{db.remove(skipId);render();});", 'undo skip')
one("const existing=rec('journal').find(j=>j.date===dayKey()&&!j.achievement&&!j.workoutPhoto&&!j.englishPractice);", "const existing=diaryEntries(rec('journal')).find(j=>j.date===dayKey());", 'mood diary selector')
one("const j=rec('journal').find(j=>j.date===dayKey()&&!j.achievement&&!j.workoutPhoto&&!j.englishPractice);", "const j=diaryEntries(rec('journal')).find(j=>j.date===dayKey());", 'journal selector')
one("db.remove(id);toast('Movido a la papelera.');", "db.remove(id);toast('Movido a la papelera.',()=>{db.restore(id);render();});", 'undo delete')
one("modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});", "modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModalSafely();}});", 'backdrop safe close')

# Excluir datos técnicos del buscador global.
one("(kind!=='project'||r.category!=='subject')&&!(kind==='journal'&&r.englishPractice)&&", "(kind!=='project'||r.category!=='subject')&&!(kind==='journal'&&!isDiaryEntry(r)&&!r.achievement)&&", 'search filters')

main.write_text(s)

# enhancements deja de inyectar agua en Progreso: ahora forma parte de la vista real.
ep=ROOT/'src/enhancements.js'
e=ep.read_text().replace('decorateWaterProgress();','')
ep.write_text(e)

print('Consolidación HCI aplicada')
