import fs from 'node:fs';

const exact=(src,from,to,label)=>{const n=src.split(from).length-1;if(n!==1)throw new Error(`${label}: ${n} coincidencias`);return src.replace(from,to);};
const regex=(src,re,to,label)=>{const matches=src.match(re);if(!matches)throw new Error(`${label}: sin coincidencias`);return src.replace(re,to);};

let main=fs.readFileSync('src/main.js','utf8');
main=exact(main,"import {dailyPlannerLayout} from './daily-planner.js';","import {dailyPlannerLayout} from './daily-planner.js';\nimport {searchLocalSpace,searchLibraryCatalog} from './global-search.js';",'import global search');
main=exact(main,"const readingTitle=r=>catalogBook(r.bookId)?.titulo||r.bookTitle||get('book',r.bookId)?.title||'Lectura libre';","const readingTitle=r=>catalogBook(r.bookId)?.titulo||r.bookTitle||'Lectura libre';",'reading title sin fallback');
main=exact(main,"if(rec('book').length&&!settings().legacyBooksRetiredAt)retireLegacyBooks(db);","if(!settings().legacyBooksRetiredAt)retireLegacyBooks(db);",'retiro legado compatible');
main=regex(main,/function currentReading\(\)\{[\s\S]*?\nfunction readingWidget\(\)/,"function currentReading(){const c=catalog();const b=c.allowed?c.reading[0]:null;return b?{id:'lib:'+b.id,title:b.titulo,author:b.autor,page:b.pagina_actual||0,pages:b.paginas,more:c.reading.length-1}:null;}\nfunction readingWidget()",'current reading catálogo único');
main=exact(main,"const c=catalog(),books=c.allowed?c.reading.map(b=>['lib:'+b.id,b.titulo]):rec('book').map(b=>[b.id,b.title]);","const c=catalog(),books=c.allowed?c.reading.map(b=>['lib:'+b.id,b.titulo]):[];",'reading form catálogo único');
main=regex(main,/\n if\(kind==='book'\)fields=[^\n]*\n/,"\n",'editor book legado');
main=exact(main,"...(catalog().allowed?catalog().reading.map(b=>['lib:'+b.id,b.titulo]):rec('book').map(b=>[b.id,b.title]))","...(catalog().allowed?catalog().reading.map(b=>['lib:'+b.id,b.titulo]):[])",'citas catálogo único');
main=exact(main,",book:'Tu libro'",'', 'titulo editor book');
main=regex(main,/\n if\(kind==='book'\)\{[^\n]*\}/,"",'guardado book legado');
main=regex(main,/function catalogReadingCards\(\)[\s\S]*?\nfunction readingCompanionView\(\)/,"function readingCompanionView()",'helper catálogo viejo');
main=regex(main,/function libraryView\(\)[\s\S]*?\nfunction vocabView\(\)/,"function vocabView()",'vista biblioteca vieja');
main=exact(main,"finishedBooks=c.allowed?(c.finishedCount||0):rec('book').filter(b=>b.status==='finished').length","finishedBooks=c.finishedCount||0",'progreso libros catálogo único');
main=exact(main,"[catalog().allowed?'library':'book','BookOpen','Un libro',catalog().allowed?'Abrir el catálogo principal':'Tu próxima lectura']","['library','BookOpen','Un libro','Abrir el catálogo principal']",'crear libro abre biblioteca');

main=regex(main,/function searchModal\(\)\{[\s\S]*?\nasync function action\(a,el\)\{/,`function searchModal(){
 showModal('Encontrá lo que buscás',\`<label>Buscar en todo Habits<input id="global-search" type="search" placeholder="Tarea, hábito, evento, libro, diario…" autofocus autocomplete="off"></label><div id="search-results"><p class="muted">Escribí para buscar en todo tu espacio.</p></div>\`);
 const inputEl=modal.querySelector('#global-search'),out=modal.querySelector('#search-results');let sequence=0,timer=0;
 const renderResults=(local,books,loading=false)=>{const rows=[...local,...books];out.innerHTML=rows.map(r=>btn(\`<strong>\${esc(r.title)}</strong><small>\${esc(r.label)}\${r.subtitle?' · '+esc(r.subtitle):''}</small>\`,r.kind==='library-book'?'library-book':'search-result',\`data-kind="\${esc(r.kind)}" data-id="\${esc(r.id)}"\`,'search-result')).join('')||(loading?'<p class="muted">Buscando también en Biblioteca…</p>':'<p class="muted">No encontramos coincidencias.</p>');};
 inputEl.oninput=e=>{const q=e.target.value.trim(),token=++sequence;clearTimeout(timer);if(!q){out.innerHTML='<p class="muted">Escribí para buscar en todo tu espacio.</p>';return;}const local=searchLocalSpace(q,{records:rec,isDiaryEntry,limit:24});renderResults(local,[],q.length>=2);timer=setTimeout(async()=>{const books=await searchLibraryCatalog(q,{limit:10});if(token!==sequence)return;renderResults(local,books,false);},180);};
}
async function action(a,el){`,'búsqueda global');

main=regex(main,/if\(a==='library-search'\)\{[^}]*\}if\(a==='library'\)/,"if(a==='library-book'){window.libraryQuery='';window.libraryBookId=el.dataset.id||'';view='library';modal.close();render();return;}if(a==='library')",'abrir libro global');
main=exact(main,"if(view==='library')void mountNativeLibrary(document.querySelector('[data-library-native-host]'),{query:window.libraryQuery||''}).catch(err=>{console.error(err);toast('No se pudo abrir Biblioteca: '+err.message);});","if(view==='library')void mountNativeLibrary(document.querySelector('[data-library-native-host]'),{query:window.libraryQuery||'',bookId:window.libraryBookId||''}).then(()=>{window.libraryBookId='';}).catch(err=>{console.error(err);toast('No se pudo abrir Biblioteca: '+err.message);});",'montaje libro directo');
if(main.includes("rec('book')")||main.includes("get('book'"))throw new Error('Todavía quedan fallbacks book en main.js');
fs.writeFileSync('src/main.js',main);

let planner=fs.readFileSync('src/daily-planner.js','utf8');
planner=exact(planner,"const hours=Array.from({length:16},(_,i)=>String(i+6).padStart(2,'0'));","const hours=Array.from({length:16},(_,i)=>String(i+6).padStart(2,'0'));\nconst moods=[['😔','Difícil'],['😐','Más o menos'],['🙂','Bien'],['😊','Muy bien'],['🤩','Con mucha energía']];",'moods constantes');
planner=exact(planner,"function currentPlan(date){return planForDate(db.records(DAILY_PLAN_KIND),date);}",`function moodForDate(date){return db.records('journal').find(j=>j.date===date&&!j.achievement&&!j.workoutPhoto&&!j.englishPractice&&Number(j.mood));}
function moodSection(date){const selected=Number(moodForDate(date)?.mood)||0;return \`<section class="planner-section planner-mood-section" aria-labelledby="planner-mood-title"><div class="planner-section-title"><h3 id="planner-mood-title">¿Cómo te sentís hoy?</h3><small>elegí un emoji</small></div><div class="planner-moods" role="radiogroup" aria-label="Cómo te sentís hoy">\${moods.map(([emoji,label],i)=>{const value=i+1,chosen=selected===value;return \`<button type="button" class="planner-mood \${chosen?'chosen':''}" data-action="mood" data-mood="\${value}" role="radio" aria-checked="\${chosen}" aria-label="\${label}: \${value} de 5"><span aria-hidden="true">\${emoji}</span><small>\${label}</small></button>\`;}).join('')}</div><p class="planner-mood-note">Tu respuesta se guarda en el mismo registro de ánimo de Mi día y Mi diario.</p></section>\`;}
function currentPlan(date){return planForDate(db.records(DAILY_PLAN_KIND),date);}`,'mood nativo');
planner=exact(planner,"  <div class=\"planner-grid\">","  ${moodSection(date)}\n  <div class=\"planner-grid\">",'render mood planner');
fs.writeFileSync('src/daily-planner.js',planner);

let css=fs.readFileSync('src/daily-planner.css','utf8');
const moodCss=fs.readFileSync('src/daily-planner-mood.css','utf8');
if(!css.includes('.planner-mood-section'))css+=`\n/* Ánimo nativo de Agenda del día */\n${moodCss}\n`;
fs.writeFileSync('src/daily-planner.css',css);

let index=fs.readFileSync('index.html','utf8');
index=exact(index,'<script type="module" src="/src/main.js"></script><script type="module" src="/src/daily-planner-mood.js"></script>','<script type="module" src="/src/main.js"></script>','script mood');
fs.writeFileSync('index.html',index);

let host=fs.readFileSync('src/library-native-host.js','utf8');
host=exact(host,"export async function mountNativeLibrary(host,{query=''}={}){","export async function mountNativeLibrary(host,{query='',bookId=''}={}){",'host book id');
host=exact(host," await applyQuery(query);\n}"," await applyQuery(query);\n if(bookId)window.dispatchEvent(new CustomEvent('habits:library-open-book',{detail:{id:Number(bookId)}}));\n}",'dispatch book');
fs.writeFileSync('src/library-native-host.js',host);

let library=fs.readFileSync('src/biblioteca-main.js','utf8');
library=regex(library,/function dialog\(title,body,save\)\{[^\n]*\}/,`function dialog(title,body,save){modal.innerHTML=\`<div class="modal-heading library-modal-heading"><h2>\${u.esc(title)}</h2><button type="button" class="button outline" data-action="close">Cerrar</button></div>\${save?'<form>':''}\${body}\${save?'<div class="modal-footer"><button class="button primary" type="submit">Guardar</button></div></form>':''}\`;if(!modal.open)modal.showModal();if(save)modal.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await save(new FormData(e.target));modal.close();await reload();toast('Guardado.');}catch(error){toast(error.message);}finally{b.disabled=false;}};}`,'modal biblioteca patrón Habits');
library=regex(library,/function bookDetail\(id\)\{[\s\S]*?\nfunction selectBook\(title,callback\)/,`function bookDetail(id){const b=s.book(id);if(!b)return;const history=s.data.readings.filter(r=>r.libro_id===id);const details=Object.entries(b).filter(([k,v])=>!['id','owner_id','portada','descripcion','titulo','autor'].includes(k)&&v!==null&&v!=='').map(([k,v])=>\`<div><dt>\${u.esc(k.replaceAll('_',' '))}</dt><dd>\${u.esc(v)}</dd></div>\`).join('');dialog(b.titulo,\`<article class="panel library-book-detail"><div class="library-book-detail-hero">\${s.covers.has(b.id)?\`<img class="library-book-detail-cover" src="\${u.esc(s.covers.get(b.id))}" alt="Portada de \${u.esc(b.titulo)}">\`:'<div class="library-book-detail-cover library-book-detail-cover-empty">Sin portada</div>'}<div class="library-book-detail-copy"><p class="eyebrow">FICHA DEL LIBRO</p><h3>\${u.esc(b.autor||'Autor no registrado')}</h3><p>\${u.esc(b.descripcion||'Sin sinopsis registrada.')}</p></div></div><dl class="library-book-detail-meta">\${details||'<div><dt>Información</dt><dd>Sin datos adicionales.</dd></div>'}</dl></article>\${canWrite?\`<section class="panel library-book-detail-actions"><h3>Acciones</h3><div class="button-row">\${['edit-book','favorite','start-book','add-next-book','cover','remove-cover','internet','phone-cover','trash-book'].map((a,i)=>button(['Editar','Favorito ☆','Empezar lectura','Leer después','Subir / cambiar portada','Quitar portada','Buscar datos y portadas','Cargar desde celular','Enviar a papelera'][i],a,id)).join('')}</div></section>\`:''}<section class="panel library-book-detail-history"><h3>Historial de lectura</h3>\${history.map(r=>\`<p>\${u.esc(r.fecha)} · página \${r.pagina} · \${r.paginas_leidas} páginas leídas</p>\`).join('')||'<p class="muted">Sin registros.</p>'}</section>\`);}
function selectBook(title,callback)`,'ficha libro patrón Habits');
library=exact(library,"document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el||!(root?.contains(el)||modal?.contains(el)))return;","window.addEventListener('habits:library-open-book',event=>{const id=Number(event.detail?.id);if(id&&s.book(id))bookDetail(id);});\ndocument.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el||!(root?.contains(el)||modal?.contains(el)))return;",'evento abrir libro');
fs.writeFileSync('src/biblioteca-main.js',library);

let libCss=fs.readFileSync('src/library-native.css','utf8');
libCss+=`\n.library-native-modal{border:1px solid var(--line);border-radius:18px;padding:28px;background:var(--panel);color:var(--text);width:min(560px,calc(100% - 30px));max-height:90dvh;box-shadow:0 25px 100px #18291d22}.library-native-modal:has(.library-book-detail){width:min(760px,calc(100% - 30px))}.library-native-modal::backdrop{background:#18291d66;backdrop-filter:blur(3px)}.library-modal-heading{margin-bottom:20px}.library-book-detail{margin-bottom:16px}.library-book-detail-hero{display:grid;grid-template-columns:150px 1fr;gap:20px;align-items:start}.library-book-detail-cover{display:block;width:150px;aspect-ratio:2/3;object-fit:cover;border-radius:8px;border:1px solid var(--line);background:var(--soft)}.library-book-detail-cover-empty{display:grid;place-items:center;color:var(--muted);font-size:12px;text-align:center;padding:12px}.library-book-detail-copy h3{font-family:var(--serif);font-size:21px;font-weight:400;margin-bottom:8px}.library-book-detail-copy>p:not(.eyebrow){font-size:12px;color:var(--muted);white-space:pre-wrap}.library-book-detail-meta{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 16px;margin:20px 0 0}.library-book-detail-meta>div{padding:10px 0;border-top:1px solid var(--line);min-width:0}.library-book-detail-meta dt{font-size:9px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}.library-book-detail-meta dd{margin:4px 0 0;font-size:12px;overflow-wrap:anywhere}.library-book-detail-actions .button-row{align-items:stretch}.library-book-detail-history p{font-size:12px;margin:8px 0}.library-book-detail-history p:last-child{margin-bottom:0}@media(max-width:650px){.library-native-modal{padding:23px 20px;border-radius:15px}.library-book-detail-hero{grid-template-columns:92px 1fr;gap:14px}.library-book-detail-cover{width:92px}.library-book-detail-meta{grid-template-columns:1fr}.library-book-detail-actions .button-row{display:grid;grid-template-columns:1fr 1fr}.library-book-detail-actions .lib-button{width:100%}}\n`;
fs.writeFileSync('src/library-native.css',libCss);

let moodTest=fs.readFileSync('tests/daily-planner-mood.test.js','utf8');
moodTest=`import test from 'node:test';\nimport assert from 'node:assert/strict';\nimport {readFile,access} from 'node:fs/promises';\nconst read=path=>readFile(new URL('../'+path,import.meta.url),'utf8');\ntest('Agenda del día integra ánimo nativamente sin parche de DOM',async()=>{const [planner,css,index]=await Promise.all([read('src/daily-planner.js'),read('src/daily-planner.css'),read('index.html')]);assert.match(planner,/db\\.records\\('journal'\\)/);assert.match(planner,/data-action=\\"mood\\"/);assert.match(planner,/¿Cómo te sentís hoy\\?/);assert.match(planner,/role=\\"radiogroup\\"/);assert.doesNotMatch(planner,/MutationObserver/);assert.match(css,/\\.planner-mood\\.chosen/);assert.doesNotMatch(index,/daily-planner-mood\\.js/);await assert.rejects(access(new URL('../src/daily-planner-mood.js',import.meta.url)));await assert.rejects(access(new URL('../src/daily-planner-mood.css',import.meta.url)));});\n`;
fs.writeFileSync('tests/daily-planner-mood.test.js',moodTest);
