import {esc,ESTADOS,fmtDate,today,readingPercent,deweyFmt,unique,overdue} from './utils.js';
import {starsHtml} from './book-editor.js';
export const bookOption=b=>`${b.titulo} — ${b.autor||'Sin autor'} · ${b.codigo_p||'Sin código'} Nº ${b.item||b.id}`;
const btn=(label,action,id,extra='')=>`<button type="button" data-action="${action}" data-id="${id}" ${extra}>${label}</button>`;
const field=(name,label,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value??'')}" ${extra}></label>`;
const status='<p role="status" aria-live="polite"></p>';
const picker=(s,type)=>`<label>Libro<input name="book" list="books-${type}" required placeholder="Escribí el título o elegí de la lista" value="${esc(s.selectedBook?bookOption(s.book(s.selectedBook)):'')}"><datalist id="books-${type}">${s.data.books.filter(b=>!b.eliminado&&b.lista==='catalogo'&&(type!=='loan'||!s.data.loans.some(l=>l.libro_id===b.id&&l.activo))).map(b=>`<option value="${esc(bookOption(b))}">`).join('')}</datalist></label>`;
const cover=(b,s)=>s.covers.has(b.id)?`<img src="${esc(s.covers.get(b.id))}" alt="Portada de ${esc(b.titulo)}">`:`<div class="sin-portada">${esc(b.titulo)}</div>`;
export function originalReadings(s){
 const current=s.data.books.filter(b=>!b.eliminado&&['leyendo','releyendo'].includes(b.estado_lectura)).sort((a,b)=>a.titulo.localeCompare(b.titulo,'es'));
 return `<h1>📖 Estoy leyendo</h1><p class="nota">Acá agregás el libro que estás leyendo ahora. La app guarda qué día empezó, qué día terminó y tu nota con estrellas.</p>
 ${s.canWrite?`<section class="panel"><h3>Agregar libro a lectura actual</h3><form data-transition="start" class="form-linea">${picker(s,'reading')}${field('start','Empezó',today(),'date','required')}<button type="submit">Empezar lectura</button>${status}</form></section>`:''}
 <div class="lecturas-grid">${current.map(b=>`<article class="lectura-card">${btn(cover(b,s),'book',b.id,'class="lectura-portada"')}<div class="lectura-info"><small class="dewey-card">${esc(deweyFmt(b.dewey)||'Sin Dewey')}</small><h3>${btn(esc(b.titulo),'book',b.id,'class="link"')}</h3><p>${esc(b.autor||'')}</p><p class="nota">Empezado: ${fmtDate(b.fecha_inicio)}</p>${b.paginas?`<div class="lectura-avance"><strong>${readingPercent(b)}%</strong><span>de lectura</span></div><div class="progreso chico"><div class="progreso-barra" style="width:${readingPercent(b)}%"></div></div>`:''}<small>Pág. ${b.pagina_actual||0} de ${b.paginas||'—'} · ${readingPercent(b)}%</small>
 ${s.canWrite?`<form data-transition="page" data-book="${b.id}" class="form-pagina-lectura">${field('page','Estoy en la página',b.pagina_actual||0,'number',`required min="0" ${b.paginas?'max="'+b.paginas+'"':''}`)}<button type="submit" class="mini secundario">Guardar página</button>${status}</form>
 <form data-transition="finish" data-book="${b.id}" class="form-concluir"><div class="fila">${field('start','Empezó',b.fecha_inicio||today(),'date','required')}${field('end','Terminó',today(),'date','required')}</div><p class="nota calculo-tiempo">El tiempo se calcula solo con las fechas de inicio y fin.</p><span>Nota</span>${starsHtml(0,true)}${field('comment','Comentario corto','','text','placeholder="Opcional"')}<button type="submit">✅ Concluí</button>${status}</form><form data-transition="abandon" data-book="${b.id}"><button type="submit" class="mini secundario">Marcar abandonado</button>${status}</form>`:''}</div></article>`).join('')||'<p class="vacio">Todavía no hay libros en lectura actual.</p>'}</div>
 <section><h3>Últimas lecturas concluidas</h3>${finishedTable(s)}</section>`;
}
export function finishedTable(s){return `<table class="tabla-mini"><thead><tr><th>Empezó</th><th>Terminó</th><th>Libro</th><th>Tiempo</th><th>Comentario</th></tr></thead><tbody>${[...s.data.finished].sort((a,b)=>String(b.fecha_fin).localeCompare(String(a.fecha_fin))).map(r=>`<tr><td>${fmtDate(r.fecha_inicio)}</td><td>${fmtDate(r.fecha_fin)}</td><td>${esc(s.book(r.libro_id)?.titulo||'Libro eliminado')}</td><td>${esc(r.tiempo_lectura|| (r.dias_lectura!=null?r.dias_lectura+' días':'—'))}</td><td>${esc(r.comentario||'')}</td></tr>`).join('')||'<tr><td colspan="5">Todavía no hay lecturas concluidas.</td></tr>'}</tbody></table>`;}
export function originalLoans(s){const active=s.data.loans.filter(l=>l.activo||l.estado==='prestado'),history=s.data.loans.filter(l=>!l.activo&&l.estado!=='prestado');return `<h1>📚 Préstamos de libros</h1><p class="nota">Usá esta pantalla para saber qué libro prestaste, a quién, cuándo volvió, si se perdió y en qué estado se devolvió.</p>${active.some(overdue)?`<p class="alerta-vencidos">⚠ Hay ${active.filter(overdue).length} préstamos vencidos.</p>`:''}
 ${s.canWrite?`<section class="panel prestamos-formulario-grande"><h3>Registrar nuevo préstamo</h3><form class="formulario original-wide-form prestamos-form-vertical" data-transition="loan">${picker(s,'loan')}<small class="nota-inline">Podés escribir el título. La app intenta encontrarlo aunque no lo elijas exacto.</small>${field('person','Prestado a','','text','required list="loan-people" placeholder="Nombre de la persona"')}<datalist id="loan-people">${unique([...s.data.people.map(p=>p.nombre),...s.data.loans.map(p=>p.persona)]).map(p=>`<option value="${esc(p)}">`).join('')}</datalist><small class="nota-inline">Si escribís una persona nueva, queda guardada como perfil para elegirla después.</small><div class="fila">${field('date','Fecha de préstamo',today(),'date','required')}${field('due','Devolver aprox.','','date')}</div><label>Notas<textarea name="notes" rows="2" placeholder="Ej: lo llevó para las vacaciones, devolver en buen estado..."></textarea></label><button type="submit">Guardar préstamo</button>${status}</form></section>`:''}
 <section class="prestamos-activos-seccion"><h3>Prestados ahora</h3><div class="prestamos-lista-vertical">${active.map(l=>{const b=s.book(l.libro_id);return `<article class="prestamo-card">${b?cover(b,s):''}<div><h4>${btn(esc(b?.titulo||'Libro eliminado'),'book',l.libro_id,'class="link"')}</h4><p>${esc(b?.autor||'')}</p><p><strong>Prestado a:</strong> ${btn(esc(l.persona),'person-history','',`data-person="${esc(l.persona)}" class="link"`)}</p><p><strong>Desde:</strong> ${fmtDate(l.fecha_prestamo)} · <strong>Devolver:</strong> ${fmtDate(l.fecha_devolucion_prevista)} ${overdue(l)?'<span class="chip chip-vencido">Vencido</span>':''}</p><p class="nota">${esc(b?.codigo_p||'')} ${b?.item?'Nº '+b.item:''}</p><p>${esc(l.notas||'')}</p>${s.canWrite?`<div class="acciones-prestamo"><details><summary>Marcar devuelto</summary><form data-transition="return" data-book="${l.libro_id}" data-loan="${l.id}">${field('condition','Estado al devolver','','text','required placeholder="Ej: impecable, con marcas, dañado..."')}<button type="submit">Guardar devolución</button>${status}</form></details>${btn('Marcar perdido','lost-loan',l.id,'class="mini peligro-suave"')}${btn('Eliminar registro','delete-loan',l.id,'class="mini peligro-suave"')}</div>`:''}</div></article>`}).join('')||'<p class="vacio">No hay libros prestados ahora.</p>'}</div></section>
 <section><h3>Historial reciente</h3><table class="tabla-mini"><thead><tr><th>Libro</th><th>Persona</th><th>Préstamo</th><th>Devuelto</th><th>Estado</th><th>Estado al devolver</th><th>Notas</th></tr></thead><tbody>${history.map(l=>`<tr><td>${esc(s.book(l.libro_id)?.titulo||'Libro eliminado')}</td><td>${btn(esc(l.persona),'person-history','',`data-person="${esc(l.persona)}" class="link"`)}</td><td>${fmtDate(l.fecha_prestamo)}</td><td>${fmtDate(l.fecha_devuelto)}</td><td>${esc(l.estado||'devuelto')}</td><td>${esc(l.estado_devolucion||'—')}</td><td>${esc(l.notas||'')}</td></tr>`).join('')||'<tr><td colspan="7">Sin historial todavía.</td></tr>'}</tbody></table></section>`;}
