import {esc,today,daysBetween} from './utils.js';
export function extraStatistics(data,day=today()){
 const books=data.books.filter(b=>!b.eliminado),catalog=books.filter(b=>b.lista==='catalogo'),byId=new Map(books.map(b=>[b.id,b])),finished=data.finished.filter(r=>byId.has(r.libro_id)),loans=data.loans;
 const group=(rows,key)=>Object.entries(rows.reduce((a,r)=>{const k=key(r);if(k)a[k]=(a[k]||0)+1;return a;},{})).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));
 const dates=new Set(data.readings.filter(r=>r.paginas_leidas>0).map(r=>String(r.fecha).slice(0,10)));let cursor=new Date(day+'T12:00:00Z'),streak=0;const key=()=>cursor.toISOString().slice(0,10);if(!dates.has(key()))cursor.setUTCDate(cursor.getUTCDate()-1);while(dates.has(key())){streak++;cursor.setUTCDate(cursor.getUTCDate()-1);}
 const durations=finished.map(r=>Number(r.dias_lectura??daysBetween(r.fecha_inicio,r.fecha_fin))).filter(n=>Number.isFinite(n)&&n>0);
 return {streak,average:durations.length?Math.round(durations.reduce((a,b)=>a+b,0)/durations.length*10)/10:null,dewey:group(catalog,b=>b.dewey?String(Math.floor(Number(b.dewey)/100)*100).padStart(3,'0'):'Sin Dewey'),months:group(catalog,b=>b.fecha_agregado?.slice(0,7)).sort((a,b)=>a[0].localeCompare(b[0])),genres:group(catalog.filter(b=>b.estado_lectura==='leido'),b=>b.genero||'Sin género'),ratings:books.filter(b=>b.rating).sort((a,b)=>b.rating-a.rating).slice(0,10),returned:loans.filter(l=>!l.activo&&l.estado==='devuelto').length,lost:loans.filter(l=>l.estado==='perdido').length,people:group(loans,l=>l.persona),borrowed:group(loans,l=>byId.get(l.libro_id)?.titulo||'Libro eliminado'),longest:loans.map(l=>({...l,title:byId.get(l.libro_id)?.titulo||'Libro eliminado',days:daysBetween(l.fecha_prestamo,l.fecha_devuelto||day)})).filter(l=>l.days!==null).sort((a,b)=>b.days-a.days)[0]};
}
export function extraStatisticsHtml(data){const x=extraStatistics(data),list=(title,rows)=>`<section class="lib-panel"><h3>${title}</h3>${rows.length?`<dl>${rows.map(([k,v])=>`<div class="lib-stat-line"><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`:'<p>Sin datos todavía.</p>'}</section>`;return `<div class="lib-extra-statistics">${list('Lectura y préstamos',[['Racha actual de lectura',x.streak+' días'],['Duración promedio',x.average===null?'Sin datos':x.average+' días'],['Préstamos devueltos',x.returned],['Préstamos perdidos',x.lost],['Más tiempo fuera',x.longest?x.longest.title+' · '+x.longest.days+' días':'Sin préstamos']])}${list('Clasificación Dewey',x.dewey)}${list('Adquisiciones por mes',x.months)}${list('Géneros leídos',x.genres)}${list('Mejor puntuados',x.ratings.map(b=>[b.titulo,b.rating+'/10']))}${list('Personas con más préstamos',x.people)}${list('Libros más prestados',x.borrowed)}</div>`;}
