export const ESTADOS={no_leido:'No leído',leyendo:'Leyendo',releyendo:'Releyendo',leido:'Leído',abandonado:'Abandonado'};
export const DEFAULT_CONFIG={nombre_biblioteca:'Mi biblioteca',color_principal:'#6f7f64',color_fondo:'#f5f1e8',color_texto:'#292823',color_tarjeta:'#fffdf8',fuente:'Georgia, serif',fuente_titulos:'Georgia, serif',fuente_botones:'Georgia, serif',tamano_texto:'16',tamano_titulos:'30',tamano_botones:'16',por_pagina:'200',mostrar_favoritos_catalogo:'1',vista_default:'cuadricula'};
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const clean=v=>{const s=String(v??'').trim();return s||null};
export const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export const isoDate=v=>{if(!v)return null;return String(v).slice(0,10)};
export const fmtDate=v=>{if(!v)return '—';const d=new Date(String(v).slice(0,10)+'T12:00:00');return Number.isNaN(+d)?String(v):d.toLocaleDateString('es-PY',{day:'2-digit',month:'short',year:'numeric'})};
export const stripAccents=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ñ/gi,m=>m==='Ñ'?'N':'n').toLocaleLowerCase();
export const searchHaystack=b=>stripAccents([b.titulo,b.autor,b.editorial,b.isbn,b.observaciones,b.descripcion,b.dedicatoria,b.genero,b.subdivision,b.dewey,b.codigo_p,b.item].filter(Boolean).join(' '));
export function matchesSearch(book,q){const words=stripAccents(q).split(/\s+/).filter(Boolean).slice(0,8);if(!words.length)return true;const h=searchHaystack(book);return words.every(w=>h.includes(w));}
export const deweyNumber=v=>{if(v===null||v===undefined||String(v).trim()==='')return null;const m=String(v).replace(',','.').match(/\d+(?:\.\d+)?/);return m?Number(m[0]):null};
export const deweyFmt=v=>{const s=clean(v);if(!s)return '';const n=s.replace(',','.');return /^\d{1,2}(?:\.\d+)?$/.test(n)?n.padStart(3,'0'):n};
export function normalizeAuthor(text){return stripAccents(text).replace(/[^a-z0-9 ]/g,' ').toUpperCase().replace(/\s+/g,' ').trim()}
export function cutterAuthor(author){const original=String(author??'');const normalized=normalizeAuthor(original);if(!normalized)return 'AAA';let word;if(original.includes(',')){word=normalizeAuthor(original.split(',')[0]).split(' ')[0]}else{const parts=normalized.split(' ').filter(p=>!['DE','DEL','LA','LAS','LOS','Y'].includes(p));word=parts.at(-1)||normalized.split(' ').at(-1)}return (word.slice(0,3)||'AAA').padEnd(3,'X')}
export function readingPercent(book){const total=Number(book.paginas)||0,current=Number(book.pagina_actual)||0;return total?Math.max(0,Math.min(100,Math.round(current/total*100))):0}
export function daysBetween(a,b){if(!a||!b)return null;const x=new Date(a+'T12:00:00'),y=new Date(b+'T12:00:00');return Math.max(0,Math.round((y-x)/86400000)+1)}
export function readingTimeText(days){if(days===null||days===undefined)return null;if(days===1)return '1 día';if(days<30)return `${days} días`;const months=Math.floor(days/30),rest=days%30;return rest?`${months} mes${months===1?'':'es'} y ${rest} día${rest===1?'':'s'}`:`${months} mes${months===1?'':'es'}`}
export function overdue(loan){return !!(loan?.activo&&loan.fecha_devolucion_prevista&&loan.fecha_devolucion_prevista<today())}
export function missingFields(book){const out=[];if(!clean(book.portada))out.push('portada');if(!clean(book.dewey))out.push('dewey');if(!Number(book.paginas))out.push('paginas');if(!clean(book.autor))out.push('autor');if(!clean(book.isbn))out.push('isbn');if(!clean(book.editorial))out.push('editorial');if(!clean(book.descripcion))out.push('descripcion');return out}
export const unique=(arr)=>[...new Set(arr.filter(v=>v!==null&&v!==undefined&&String(v).trim()!==''))].sort((a,b)=>String(a).localeCompare(String(b),'es',{sensitivity:'base'}));
export function configObject(rows){const c={...DEFAULT_CONFIG};for(const r of rows||[])c[r.clave]=r.valor;return c}
export function applyConfig(c){const root=document.documentElement;root.style.setProperty('--lib-main',c.color_principal||DEFAULT_CONFIG.color_principal);root.style.setProperty('--lib-bg',c.color_fondo||DEFAULT_CONFIG.color_fondo);root.style.setProperty('--lib-text',c.color_texto||DEFAULT_CONFIG.color_texto);root.style.setProperty('--lib-card',c.color_tarjeta||DEFAULT_CONFIG.color_tarjeta);root.style.fontFamily=c.fuente||DEFAULT_CONFIG.fuente;root.style.fontSize=`${Math.max(12,Math.min(22,Number(c.tamano_texto)||16))}px`}
export function downloadBlob(name,content,type='application/octet-stream'){const blob=content instanceof Blob?content:new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
export function csvText(rows,columns){const quote=v=>`"${String(v??'').replaceAll('"','""')}"`;return '\ufeff'+[columns.map(quote).join(','),...rows.map(r=>columns.map(c=>quote(r[c])).join(','))].join('\n')}
export function cleanIsbn(v){return String(v??'').replace(/[^0-9Xx]/g,'').toUpperCase()}
export function normalizeLanguage(code){const m={es:'Español',spa:'Español',en:'Inglés',eng:'Inglés',pt:'Portugués',por:'Portugués',fr:'Francés',fre:'Francés',it:'Italiano',ita:'Italiano',de:'Alemán',ger:'Alemán',la:'Latín',lat:'Latín',gn:'Guaraní',grn:'Guaraní'};return m[code]||code||null}
export function cleanHtml(v){if(!v)return null;const doc=new DOMParser().parseFromString(String(v).replace(/<br\s*\/?>/gi,'\n'),'text/html');return clean((doc.body.textContent||'').replace(/\n\s*\n+/g,'\n').slice(0,1800))}
export async function googleBooksOptions(title,author='',limit=8){const queries=[];if(author)queries.push(`intitle:${title} inauthor:${author}`);queries.push(title);const seen=new Set(),out=[];for(const q of queries){try{const r=await fetch(`https://www.googleapis.com/books/v1/volumes?q=${encodeURIComponent(q)}&maxResults=${limit}&printType=books`);if(!r.ok)continue;const data=await r.json();for(const item of data.items||[]){const i=item.volumeInfo||{},authors=(i.authors||[]).join(', ')||null,key=`${i.title||''}|${authors||''}|${i.publisher||''}`.toLowerCase();if(seen.has(key))continue;seen.add(key);const ids=i.industryIdentifiers||[];const isbn=ids.find(x=>x.type==='ISBN_13')?.identifier||ids.find(x=>x.type==='ISBN_10')?.identifier||null;let cover=i.imageLinks?.extraLarge||i.imageLinks?.large||i.imageLinks?.medium||i.imageLinks?.thumbnail||i.imageLinks?.smallThumbnail||null;if(cover)cover=cover.replace('http://','https://');out.push({fuente:'Google Books',titulo:i.title||null,autor:authors,editorial:i.publisher||null,paginas:i.pageCount||null,isbn,idioma:normalizeLanguage(i.language),descripcion:cleanHtml(i.description),portada_url:cover,categorias:i.categories||[]});if(out.length>=limit)return out}}catch{}}return out}
export async function openLibraryOptions(title,author='',limit=8){try{let url=`https://openlibrary.org/search.json?title=${encodeURIComponent(title)}&limit=${limit}&fields=title,author_name,publisher,number_of_pages_median,isbn,language,cover_i,key,subject`;if(author)url+=`&author=${encodeURIComponent(author)}`;const r=await fetch(url);if(!r.ok)return[];const data=await r.json();const out=[];for(const d of data.docs||[]){const langs=d.language||[],isbns=d.isbn||[],isbn=isbns.find(x=>String(x).length===13)||isbns[0]||null;let description=null;if(d.key){try{const dr=await fetch(`https://openlibrary.org${d.key}.json`);if(dr.ok){const detail=await dr.json();const desc=typeof detail.description==='object'?detail.description?.value:detail.description;description=cleanHtml(desc)}}catch{}}out.push({fuente:'Open Library',titulo:d.title||null,autor:(d.author_name||[]).join(', ')||null,editorial:(d.publisher||[])[0]||null,paginas:d.number_of_pages_median||null,isbn,idioma:normalizeLanguage(langs[0]),descripcion:description,portada_url:d.cover_i?`https://covers.openlibrary.org/b/id/${d.cover_i}-L.jpg`:null,categorias:(d.subject||[]).slice(0,10)})}return out}catch{return[]}}
export async function internetOptions(title,author=''){const [g,o]=await Promise.all([googleBooksOptions(title,author,8),openLibraryOptions(title,author,8)]);const all=[...g,...o],seen=new Set(),out=[];for(const x of all){const k=stripAccents(`${x.titulo}|${x.autor}|${x.editorial}`);if(!seen.has(k)){seen.add(k);out.push(x)}}return out}
export async function lookupIsbn(isbn){isbn=cleanIsbn(isbn);if(!isbn)throw new Error('Escribí un ISBN.');try{const r=await fetch(`https://www.googleapis.com/books/v1/volumes?q=isbn:${encodeURIComponent(isbn)}&maxResults=5`);if(r.ok){const d=await r.json();const i=d.items?.[0]?.volumeInfo;if(i){const ids=i.industryIdentifiers||[];let cover=i.imageLinks?.extraLarge||i.imageLinks?.large||i.imageLinks?.medium||i.imageLinks?.thumbnail||null;if(cover)cover=cover.replace('http://','https://');return {titulo:i.title||null,autor:(i.authors||[]).join(', ')||null,editorial:i.publisher||null,paginas:i.pageCount||null,isbn:ids.find(x=>x.type==='ISBN_13')?.identifier||isbn,idioma:normalizeLanguage(i.language),descripcion:cleanHtml(i.description),portada_url:cover}}} }catch{}
 try{const r=await fetch(`https://openlibrary.org/isbn/${encodeURIComponent(isbn)}.json`);if(r.ok){const d=await r.json();let author=null;if(d.authors?.[0]?.key){try{const ar=await fetch(`https://openlibrary.org${d.authors[0].key}.json`);if(ar.ok)author=(await ar.json()).name}catch{}}return {titulo:d.title||null,autor:author,editorial:(d.publishers||[])[0]||null,paginas:d.number_of_pages||null,isbn,idioma:null,descripcion:cleanHtml(typeof d.description==='object'?d.description?.value:d.description),portada_url:`https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg`}}}catch{}throw new Error('No encontré datos para ese ISBN.')}
export function fileSafeName(v){return stripAccents(v).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'archivo'}
