import {esc,ESTADOS,fmtDate,readingPercent,overdue,missingFields,unique,cutterAuthor,deweyFmt,today} from './utils.js';

const button=(label,action,attrs='',cls='lib-button')=>`<button class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;
const cover=(b,s,cls='lib-cover')=>{const src=s.covers.get(b.id);return `<div class="${cls}">${src?`<img src="${esc(src)}" alt="Portada de ${esc(b.titulo)}" loading="lazy">`:`<div class="lib-cover-fallback">${esc(b.titulo)}</div>`}</div>`};
const statusBadge=b=>`<span class="lib-badge">${esc(ESTADOS[b.estado_lectura]||b.estado_lectura||'No leído')}</span>`;
const loanFor=(b,s)=>s.data.loans.find(x=>x.libro_id===b.id&&x.activo);

export function headerView(s){
  const overdueCount=s.data.loans.filter(overdue).length;
  const readingCount=s.data.books.filter(b=>!b.eliminado&&['leyendo','releyendo'].includes(b.estado_lectura)).length;
  const nav=[['catalogo','Catálogo'],['lecturas',`📖 Estoy leyendo${readingCount?` (${readingCount})`:''}`],['prestamos',`📚 Préstamos${overdueCount?` ⚠${overdueCount}`:''}`],['deseos','🛒 Deseos'],['proximas','📌 Leer después'],['revisar','🔎 Revisar'],['estadisticas','Estadísticas'],['etiquetas','🏷 Etiquetas'],['papelera','♻ Papelera'],['configuracion','⚙ Configuración']];
  return `<header class="lib-header"><div class="lib-header-top"><a class="lib-brand" href="./"><span class="lib-brand-mark">📚</span><span>${esc(s.config.nombre_biblioteca||'Mi biblioteca')}</span></a><a class="lib-back" href="./">← Volver a Habits</a><div class="lib-header-spacer"></div><span class="lib-user">${esc(s.user?.email||'')}</span></div><nav class="lib-nav">${nav.map(([id,label])=>button(label,'view',`data-view="${id}"`,s.view===id?'active':'')).join('')}${button('+ Agregar','new-book','','lib-button')}</nav></header>`;
}

export function catalogView(s,list='catalogo'){
  const books=s.filteredBooks(list),total=books.length,pp=s.perPage,page=Math.min(s.page,Math.max(1,Math.ceil(total/pp))),slice=books.slice((page-1)*pp,page*pp);
  const title=list==='deseos'?'🛒 Lista de deseos':'Catálogo';
  const statBooks=s.data.books.filter(b=>!b.eliminado&&b.lista==='catalogo');
  return `<div class="lib-page-head"><div><h1>${title}</h1><p>${total} libro${total===1?'':'s'} · búsqueda flexible sin tildes ni orden exacto.</p></div><div class="lib-actions">${list==='catalogo'?button('+ Agregar libro','new-book'):''}${list==='deseos'?button('+ Agregar deseo','new-book','data-list="deseos"'):''}</div></div>
  ${list==='catalogo'?`<div class="lib-stats-mini"><div class="lib-stat"><strong>${statBooks.length}</strong><span>en catálogo</span></div><div class="lib-stat"><strong>${statBooks.filter(b=>b.favorito).length}</strong><span>favoritos</span></div><div class="lib-stat"><strong>${statBooks.filter(b=>b.autografiado).length}</strong><span>autografiados</span></div><div class="lib-stat"><strong>${s.data.loans.filter(x=>x.activo).length}</strong><span>prestados ahora</span></div></div>`:''}
  <section class="lib-panel"><div class="lib-toolbar"><input id="catalog-q" class="lib-input" type="search" value="${esc(s.filters.q)}" placeholder="Título, autor, LR 618, ISBN…"><select id="filter-genero" class="lib-select"><option value="">Todos los géneros</option>${s.filterOptions.generos.map(v=>`<option ${s.filters.genero===v?'selected':''}>${esc(v)}</option>`).join('')}</select><select id="filter-codigo" class="lib-select"><option value="">Todos los propietarios</option>${s.filterOptions.codigos.map(v=>`<option ${s.filters.codigo_p===v?'selected':''}>${esc(v)}</option>`).join('')}</select><select id="filter-idioma" class="lib-select"><option value="">Todos los idiomas</option>${s.filterOptions.idiomas.map(v=>`<option ${s.filters.idioma===v?'selected':''}>${esc(v)}</option>`).join('')}</select><select id="filter-estado" class="lib-select"><option value="">Todos los estados</option>${Object.entries(ESTADOS).map(([k,v])=>`<option value="${k}" ${s.filters.estado_lectura===k?'selected':''}>${v}</option>`).join('')}</select></div><div class="lib-actions" style="margin-bottom:14px">${button('Buscar','apply-filters','','lib-button small')}${button('Limpiar','clear-filters','','lib-button secondary small')}${button(s.filters.favorito?'⭐ Solo favoritos':'☆ Solo favoritos','toggle-favorites','','lib-button secondary small')}${button(s.viewMode==='lista'?'▦ Cuadrícula':'☰ Lista','toggle-view-mode','','lib-button secondary small')}</div>
  ${slice.length?(s.viewMode==='lista'?bookList(slice,s):`<div class="lib-grid">${slice.map(b=>bookCard(b,s,list)).join('')}</div>`):`<div class="lib-empty">No encontré libros con esos filtros.</div>`}
  ${total>pp?`<div class="lib-pagination">${button('← Anterior','page',`data-page="${Math.max(1,page-1)}"`,'lib-button secondary small')}<span>Página ${page} de ${Math.ceil(total/pp)}</span>${button('Siguiente →','page',`data-page="${Math.min(Math.ceil(total/pp),page+1)}"`,'lib-button secondary small')}</div>`:''}</section>`;
}

function bookCard(b,s,list){const loan=loanFor(b,s),pct=readingPercent(b);return `<article class="lib-book-card"><button data-action="book" data-id="${b.id}" style="padding:0;border:0;background:none;cursor:pointer;text-align:inherit">${cover(b,s)}<div class="lib-badges">${statusBadge(b)}${b.favorito?'<span class="lib-badge">⭐</span>':''}${b.autografiado?'<span class="lib-badge">✍️</span>':''}${loan?`<span class="lib-badge ${overdue(loan)?'danger':''}">Prestado</span>`:''}</div></button><div class="lib-book-body"><div class="lib-book-meta"><span>${esc(deweyFmt(b.dewey)||'Sin Dewey')}</span>${b.codigo_p?`<span>${esc(b.codigo_p)}-${esc(b.item||'')}</span>`:''}</div><h3>${esc(b.titulo)}</h3><p>${esc(b.autor||'Sin autor registrado')}</p>${['leyendo','releyendo'].includes(b.estado_lectura)&&b.paginas?`<progress class="lib-progress" max="100" value="${pct}"></progress><small>${b.pagina_actual||0} / ${b.paginas} · ${pct}%</small>`:''}<div class="lib-book-actions">${list==='deseos'?`${button('¡Lo compré! 🎉','buy-book',`data-id="${b.id}"`,'lib-button small')}${button('Quitar','trash-book',`data-id="${b.id}"`,'lib-button secondary small')}`:button('Ver ficha →','book',`data-id="${b.id}"`,'lib-button secondary small')}</div></div></article>`}
function bookList(books,s){return `<div class="lib-list">${books.map(b=>{const loan=loanFor(b,s);return `<div class="lib-row">${cover(b,s,'lib-thumb')}<button data-action="book" data-id="${b.id}" style="border:0;background:none;text-align:left;cursor:pointer"><strong>${esc(b.titulo)}</strong><br><small>${esc(b.autor||'Sin autor')}</small></button><span>${esc(deweyFmt(b.dewey)||'—')}</span><span>${esc(b.codigo_p||'—')}${b.item?`-${b.item}`:''}</span><span>${esc(b.genero||'—')}</span><span>${esc(ESTADOS[b.estado_lectura]||'—')}</span><span>${loan?`Prestado a ${esc(loan.persona)}`:'Disponible'}</span>${button('Ver','book',`data-id="${b.id}"`,'lib-button secondary small')}</div>`}).join('')}</div>`}

export function readingsView(s){const current=s.data.books.filter(b=>!b.eliminado&&['leyendo','releyendo'].includes(b.estado_lectura)).sort((a,b)=>a.titulo.localeCompare(b.titulo,'es'));return `<div class="lib-page-head"><div><h1>📖 Estoy leyendo</h1><p>Actualizá la página actual, concluí o abandoná una lectura.</p></div>${button('Agregar libro a lectura actual','start-reading')}</div><div class="lib-reading-list">${current.map(b=>{const pct=readingPercent(b);return `<article class="lib-panel lib-reading-card">${cover(b,s,'lib-thumb')}<div><button data-action="book" data-id="${b.id}" style="border:0;background:none;padding:0;text-align:left;cursor:pointer"><h3>${esc(b.titulo)}</h3></button><p class="lib-muted">${esc(b.autor||'')} · empezó ${fmtDate(b.fecha_inicio)}</p><progress class="lib-progress" max="100" value="${pct}"></progress><strong>${b.pagina_actual||0} / ${b.paginas||'—'} páginas · ${pct}%</strong></div><div class="lib-actions">${button('Actualizar página','update-page',`data-id="${b.id}"`,'lib-button secondary small')}${button('✅ Concluí','finish-reading',`data-id="${b.id}"`,'lib-button small')}${button('Abandonar','abandon-reading',`data-id="${b.id}"`,'lib-button secondary small')}</div></article>`}).join('')||'<div class="lib-empty">No hay libros en lectura actual.</div>'}</div><div class="lib-page-head" style="margin-top:28px"><div><h2>Últimas lecturas concluidas</h2></div></div><section class="lib-panel"><div class="lib-table-wrap"><table class="lib-table"><thead><tr><th>Libro</th><th>Inicio</th><th>Fin</th><th>Tiempo</th><th>Comentario</th></tr></thead><tbody>${s.data.finished.slice(0,30).map(r=>{const b=s.book(r.libro_id);return `<tr><td>${esc(b?.titulo||'Libro eliminado')}</td><td>${fmtDate(r.fecha_inicio)}</td><td>${fmtDate(r.fecha_fin)}</td><td>${esc(r.tiempo_lectura||'—')}</td><td>${esc(r.comentario||'')}</td></tr>`}).join('')||'<tr><td colspan="5">Todavía no hay lecturas concluidas.</td></tr>'}</tbody></table></div></section>`}

export function loansView(s){const active=s.data.loans.filter(x=>x.activo).sort((a,b)=>Number(overdue(b))-Number(overdue(a))||String(a.fecha_devolucion_prevista||'9999').localeCompare(String(b.fecha_devolucion_prevista||'9999'))),history=s.data.loans.filter(x=>!x.activo).slice(0,30);return `<div class="lib-page-head"><div><h1>📚 Préstamos de libros</h1><p>Personas, vencimientos e historial.</p></div>${button('Registrar nuevo préstamo','new-loan')}</div><div class="lib-loan-list">${active.map(l=>{const b=s.book(l.libro_id);return `<article class="lib-panel lib-loan-card">${b?cover(b,s,'lib-thumb'):''}<div><h3>${esc(b?.titulo||'Libro eliminado')}</h3><p>Prestado a ${button(esc(l.persona),'person-history',`data-person="${esc(l.persona)}"`,'lib-button ghost small')}</p><p class="${overdue(l)?'lib-overdue':'lib-muted'}">Desde ${fmtDate(l.fecha_prestamo)} · prevista ${fmtDate(l.fecha_devolucion_prevista)}</p>${l.notas?`<p>${esc(l.notas)}</p>`:''}</div><div class="lib-actions">${button('Guardar devolución','return-loan',`data-id="${l.id}"`,'lib-button small')}${button('Marcar perdido','lost-loan',`data-id="${l.id}"`,'lib-button secondary small')}${button('Eliminar registro','delete-loan',`data-id="${l.id}"`,'lib-button secondary small')}</div></article>`}).join('')||'<div class="lib-empty">No hay libros prestados ahora.</div>'}</div><div class="lib-page-head" style="margin-top:28px"><h2>Historial reciente</h2></div><section class="lib-panel"><div class="lib-table-wrap"><table class="lib-table"><thead><tr><th>Libro</th><th>Persona</th><th>Préstamo</th><th>Devuelto</th><th>Estado</th></tr></thead><tbody>${history.map(l=>`<tr><td>${esc(s.book(l.libro_id)?.titulo||'Libro eliminado')}</td><td>${button(esc(l.persona),'person-history',`data-person="${esc(l.persona)}"`,'lib-button ghost small')}</td><td>${fmtDate(l.fecha_prestamo)}</td><td>${fmtDate(l.fecha_devuelto)}</td><td>${esc(l.estado||'devuelto')}</td></tr>`).join('')||'<tr><td colspan="5">Sin historial todavía.</td></tr>'}</tbody></table></div></section>`}

export function nextReadsView(s){const books=s.data.books.filter(b=>!b.eliminado&&b.lista==='catalogo'&&b.proxima_lectura).sort((a,b)=>a.titulo.localeCompare(b.titulo,'es'));return `<div class="lib-page-head"><div><h1>📌 Quiero leer después</h1><p>Tu lista de próximas lecturas.</p></div>${button('Agregar a leer después','add-next')}</div><div class="lib-grid">${books.map(b=>`<article class="lib-book-card">${cover(b,s)}<div class="lib-book-body"><h3>${b.favorito?'⭐ ':''}${esc(b.titulo)}</h3><p>${esc(b.autor||'')}</p><div class="lib-book-actions">${button('📖 Empezar a leer','start-book',`data-id="${b.id}"`,'lib-button small')}${button('Quitar de la lista','remove-next',`data-id="${b.id}"`,'lib-button secondary small')}</div></div></article>`).join('')||'<div class="lib-empty">Todavía no marcaste próximas lecturas.</div>'}</div>`}

export function reviewView(s){const key=s.reviewKey,labels={all:'Todos',portada:'Sin portada',dewey:'Sin Dewey',paginas:'Sin páginas',autor:'Sin autor',isbn:'Sin ISBN',editorial:'Sin editorial',descripcion:'Sin descripción'},all=s.data.books.filter(b=>!b.eliminado&&b.lista==='catalogo'),books=key==='all'?all:all.filter(b=>missingFields(b).includes(key));return `<div class="lib-page-head"><div><h1>🔎 Libros para revisar</h1><p>Encontrá fichas incompletas sin perder nada de lo ya cargado.</p></div></div><div class="lib-tabs">${Object.entries(labels).map(([k,v])=>button(`${v}${k==='all'?'':` · ${all.filter(b=>missingFields(b).includes(k)).length}`}`,'review-filter',`data-key="${k}"`,k===key?'lib-chip active':'lib-chip')).join('')}</div><div class="lib-review-list">${books.slice(0,500).map(b=>`<article class="lib-panel lib-review-card">${cover(b,s,'lib-thumb')}<div><h3>${esc(b.titulo)}</h3><p>${esc(b.autor||'Sin autor')}</p><div class="lib-book-meta">${missingFields(b).map(x=>`<span class="lib-badge warn">Sin ${esc(x)}</span>`).join('')}</div></div>${button('Completar →','edit-book',`data-id="${b.id}"`,'lib-button secondary small')}</article>`).join('')||'<div class="lib-empty">No hay libros pendientes para este filtro.</div>'}</div>`}

export function trashView(s){const books=s.data.books.filter(b=>b.eliminado).sort((a,b)=>String(b.fecha_eliminado||'').localeCompare(String(a.fecha_eliminado||'')));return `<div class="lib-page-head"><div><h1>♻ Papelera</h1><p>Restaurá libros o eliminá definitivamente.</p></div>${books.length?button('Vaciar papelera definitivamente','empty-trash','','lib-button danger'):''}</div><div class="lib-grid">${books.map(b=>`<article class="lib-book-card">${cover(b,s)}<div class="lib-book-body"><h3>${esc(b.titulo)}</h3><p>Eliminado ${fmtDate(b.fecha_eliminado)}</p><div class="lib-book-actions">${button('Restaurar','restore-book',`data-id="${b.id}"`,'lib-button small')}${button('Eliminar','delete-forever',`data-id="${b.id}"`,'lib-button danger small')}</div></div></article>`).join('')||'<div class="lib-empty">La papelera está vacía.</div>'}</div>`}

export function statsView(s){const books=s.data.books.filter(b=>!b.eliminado),catalog=books.filter(b=>b.lista==='catalogo'),year=String(new Date().getFullYear()),pagesYear=s.data.readings.filter(r=>String(r.fecha||'').startsWith(year)).reduce((n,r)=>n+Number(r.paginas_leidas||0),0),finished=s.data.finished,counts=(field,limit=15)=>Object.entries(catalog.reduce((m,b)=>{const k=b[field]||`Sin ${field}`;m[k]=(m[k]||0)+1;return m},{})).sort((a,b)=>b[1]-a[1]).slice(0,limit),genres=counts('genero'),owners=counts('codigo_p'),authors=counts('autor'),publishers=counts('editorial'),max=Math.max(1,...genres.map(x=>x[1]));const activeLoans=s.data.loans.filter(x=>x.activo).length;return `<div class="lib-page-head"><div><h1>📊 Estadísticas</h1><p>Una mirada general a la biblioteca y tus lecturas.</p></div></div><div class="lib-stat-grid"><div class="lib-stat-card"><strong>${catalog.length}</strong><span>libros en catálogo</span></div><div class="lib-stat-card"><strong>${catalog.reduce((n,b)=>n+(Number(b.paginas)||0),0).toLocaleString('es-PY')}</strong><span>páginas catalogadas</span></div><div class="lib-stat-card"><strong>${unique(catalog.map(b=>b.autor)).length}</strong><span>autores distintos</span></div><div class="lib-stat-card"><strong>${catalog.filter(b=>b.estado_lectura==='leido').length}</strong><span>libros leídos</span></div><div class="lib-stat-card"><strong>${pagesYear}</strong><span>páginas leídas en ${year}</span></div><div class="lib-stat-card"><strong>${activeLoans}</strong><span>préstamos activos</span></div><div class="lib-stat-card"><strong>${catalog.filter(b=>b.autografiado).length}</strong><span>autografiados</span></div><div class="lib-stat-card"><strong>${finished.length}</strong><span>lecturas concluidas registradas</span></div></div>${chart('Libros por género',genres,max)}${chart('Propietarios / códigos internos',owners)}${chart('Autores con más ejemplares',authors)}${chart('Editoriales con más libros',publishers)}<section class="lib-panel" style="margin-top:16px"><h2>Curiosidades</h2><div class="lib-kv"><div><span>Libro más largo</span><strong>${esc([...catalog].filter(b=>b.paginas).sort((a,b)=>b.paginas-a.paginas)[0]?.titulo||'—')}</strong></div><div><span>Libro más corto</span><strong>${esc([...catalog].filter(b=>b.paginas).sort((a,b)=>a.paginas-b.paginas)[0]?.titulo||'—')}</strong></div><div><span>Favoritos</span><strong>${catalog.filter(b=>b.favorito).length}</strong></div><div><span>Leer después</span><strong>${catalog.filter(b=>b.proxima_lectura).length}</strong></div></div></section>`}
function chart(title,rows,max=Math.max(1,...rows.map(x=>x[1]))){return `<section class="lib-panel" style="margin-top:16px"><h2>${title}</h2><div class="lib-chart-list">${rows.map(([name,n])=>`<div class="lib-chart-row"><span>${esc(name)}</span><div class="lib-bar"><i style="width:${n/max*100}%"></i></div><strong>${n}</strong></div>`).join('')||'<p class="lib-muted">Sin datos.</p>'}</div></section>`}

export function labelsView(s){const books=s.labelFilteredBooks(),selected=s.selectedLabels;return `<div class="lib-page-head"><div><h1>🏷 Etiquetas de lomo</h1><p>Elegí solo los libros que quieras imprimir.</p></div><div class="lib-actions">${button('Imprimir hoja','print-labels','','lib-button')}</div></div><section class="lib-panel"><div class="lib-label-toolbar"><input class="lib-input" id="label-q" value="${esc(s.labelFilters.q)}" placeholder="Título, autor, Dewey, ISBN…"><select class="lib-select" id="label-owner"><option value="">Propietario: todos</option>${s.filterOptions.codigos.map(v=>`<option ${s.labelFilters.codigo_p===v?'selected':''}>${esc(v)}</option>`).join('')}</select><input class="lib-input" id="label-dewey" value="${esc(s.labelFilters.dewey)}" placeholder="Dewey empieza con"><select class="lib-select" id="label-genre"><option value="">Género: todos</option>${s.filterOptions.generos.map(v=>`<option ${s.labelFilters.genero===v?'selected':''}>${esc(v)}</option>`).join('')}</select></div><div class="lib-actions" style="margin-bottom:12px">${button('Aplicar filtros','label-apply','','lib-button small')}${button('Seleccionar visibles','label-select-visible','','lib-button secondary small')}${button('Quitar visibles','label-unselect-visible','','lib-button secondary small')}${button('Seleccionar todos','label-select-all','','lib-button secondary small')}${button('Limpiar','label-clear','','lib-button secondary small')}<span class="lib-muted">${books.length} visibles · ${selected.size} seleccionados</span></div><div class="lib-label-list">${books.map(b=>`<label class="lib-label-choice"><input type="checkbox" data-label-id="${b.id}" ${selected.has(b.id)?'checked':''}><span><strong>${esc(deweyFmt(b.dewey)||'SIN')} · ${esc(b.titulo)}</strong><br><small>${esc(b.autor||'')} ${b.codigo_p?`· ${esc(b.codigo_p)}-${esc(b.item||'')}`:''}</small></span></label>`).join('')}</div></section><section class="lib-panel" style="margin-top:18px"><h2>Vista de impresión</h2><div class="lib-print-sheet">${s.data.books.filter(b=>selected.has(b.id)).map(b=>`<div class="lib-spine-label"><strong>${esc(deweyFmt(b.dewey)||'SIN')}</strong><span>${esc(cutterAuthor(b.autor))}</span><small>${esc(b.codigo_p||'')}${b.item?`-${b.item}`:''}</small></div>`).join('')||'<p class="lib-muted">Seleccioná libros para ver las etiquetas.</p>'}</div></section>`}

export function configView(s){const c=s.config;return `<div class="lib-page-head"><div><h1>⚙ Configuración</h1><p>La configuración es privada para esta biblioteca.</p></div></div><form id="config-form"><div class="lib-config-grid"><section class="lib-config-section"><h3>🏷 Nombre</h3><label class="lib-field"><span>Nombre de la biblioteca</span><input class="lib-input" name="nombre_biblioteca" value="${esc(c.nombre_biblioteca)}"></label></section><section class="lib-config-section"><h3>🎨 Colores</h3>${color('Color principal','color_principal',c.color_principal)}${color('Fondo','color_fondo',c.color_fondo)}${color('Texto','color_texto',c.color_texto)}${color('Tarjetas','color_tarjeta',c.color_tarjeta)}</section><section class="lib-config-section"><h3>🔤 Tipografía</h3><label class="lib-field"><span>Fuente general</span><select class="lib-select" name="fuente">${['Georgia, serif','Arial, sans-serif','Verdana, sans-serif','Trebuchet MS, sans-serif','system-ui, sans-serif'].map(x=>`<option ${c.fuente===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label class="lib-field"><span>Tamaño de texto</span><input class="lib-input" type="number" min="12" max="22" name="tamano_texto" value="${esc(c.tamano_texto)}"></label></section><section class="lib-config-section"><h3>📚 Catálogo</h3><label class="lib-field"><span>Vista predeterminada</span><select class="lib-select" name="vista_default"><option value="cuadricula" ${c.vista_default==='cuadricula'?'selected':''}>Cuadrícula</option><option value="lista" ${c.vista_default==='lista'?'selected':''}>Lista</option></select></label><label class="lib-field"><span>Libros por página</span><select class="lib-select" name="por_pagina">${['100','200','500','todos'].map(x=>`<option ${c.por_pagina===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="lib-check"><input type="checkbox" name="mostrar_favoritos_catalogo" ${c.mostrar_favoritos_catalogo==='1'?'checked':''}> Mostrar estrella de favoritos</label></section><section class="lib-config-section"><h3>💾 Copias y exportación</h3><p class="lib-muted lib-small">Se crea un respaldo JSON privado por día y se conservan los últimos 10.</p><div class="lib-actions">${button('Descargar último respaldo','download-backup','','lib-button secondary')}${button('Descargar CSV','export-csv','','lib-button secondary')}${button('Exportar JSON ahora','export-json','','lib-button secondary')}</div></section></div><div class="lib-actions" style="margin-top:18px"><button type="submit" class="lib-button">Guardar configuración</button></div></form>`}
function color(label,name,value){return `<label class="lib-field"><span>${label}</span><input class="lib-input" type="color" name="${name}" value="${esc(value)}"></label>`}

export function personHistoryView(s,person){const loans=s.data.loans.filter(l=>l.persona===person).sort((a,b)=>String(b.fecha_prestamo).localeCompare(String(a.fecha_prestamo)));return `<div class="lib-page-head"><div><h1>👤 Historial de préstamos: ${esc(person)}</h1></div>${button('← Volver a préstamos','view','data-view="prestamos"','lib-button secondary')}</div><section class="lib-panel"><div class="lib-table-wrap"><table class="lib-table"><thead><tr><th>Libro</th><th>Prestado</th><th>Previsto</th><th>Devuelto</th><th>Estado</th></tr></thead><tbody>${loans.map(l=>`<tr><td>${esc(s.book(l.libro_id)?.titulo||'Libro eliminado')}</td><td>${fmtDate(l.fecha_prestamo)}</td><td>${fmtDate(l.fecha_devolucion_prevista)}</td><td>${fmtDate(l.fecha_devuelto)}</td><td>${esc(l.estado||'')}</td></tr>`).join('')||'<tr><td colspan="5">Sin préstamos registrados.</td></tr>'}</tbody></table></div></section>`}

export function renderCurrentView(s){if(s.personHistory)return personHistoryView(s,s.personHistory);if(s.view==='catalogo')return catalogView(s,'catalogo');if(s.view==='deseos')return catalogView(s,'deseos');if(s.view==='lecturas')return readingsView(s);if(s.view==='prestamos')return loansView(s);if(s.view==='proximas')return nextReadsView(s);if(s.view==='revisar')return reviewView(s);if(s.view==='estadisticas')return statsView(s);if(s.view==='etiquetas')return labelsView(s);if(s.view==='papelera')return trashView(s);return configView(s)}
