import {createAutosave} from './biblioteca/autosave.js';
import {createDraft,readDraft,uploadDraft,draftPreview,draftPath,consumeDraft} from './biblioteca/draft-cover.js';
import {sortBooks,DEFAULT_COLUMNS,COLUMNS,bookHistory} from './biblioteca/catalog-tools.js';
import './biblioteca.css';
import './biblioteca-habits.css';
import './library-native.css';
import './biblioteca/original.css';
import './biblioteca/reference-adapter.css';
import {mountLibraryAssistant} from './library-assistant.js';
import {supabase,sessionAndAccess,ensureConfig,canWrite,libraryOwner,resetLibraryContext} from './biblioteca/client.js';
import * as data from './biblioteca/data.js';
import * as u from './biblioteca/utils.js';
import {headerView,renderCurrentView} from './biblioteca/views.js';
import {newBookEditorHtml,bookEditorHtml,bookEditorValues,bindBookEditor,coverEditorHtml,starsHtml} from './biblioteca/book-editor.js';
import {createDailyBackup,latestBackup} from './biblioteca/backups.js';
const params=new URL(location.href).searchParams,embedded=window.__habitsLibraryNative===true||params.get('embedded')==='1';
const root=document.querySelector('#library-app'),modal=document.querySelector('#library-modal'),initialQuery=String(window.__habitsLibraryInitialQuery||params.get('q')||'').trim();
if(!window.__habitsLibraryNative)document.body.classList.add('library-native-shell');
root.classList.add('library-original');modal.classList.add('library-original');
const button=(label,action,id='')=>`<button type="button" class="lib-button secondary" data-action="${action}" data-id="${id}">${label}</button>`;
const field=(name,label,value='',type='text',extra='')=>`<label class="lib-field">${label}<input class="lib-input" name="${name}" type="${type}" value="${u.esc(value??'')}" ${extra}></label>`;
const text=(name,label,value='')=>`<label class="lib-field">${label}<textarea class="lib-input" name="${name}" rows="4">${u.esc(value??'')}</textarea></label>`;
const s={user:null,embedded,libraries:[],members:[],canManage:false,data:{books:[],readings:[],finished:[],people:[],loans:[],config:[]},config:u.DEFAULT_CONFIG,covers:new Map(),view:'catalogo',page:1,perPage:24,viewMode:'cuadricula',reviewKey:'all',personHistory:null,filters:{q:initialQuery,genero:'',codigo_p:'',idioma:'',estado_lectura:'',favorito:false},selectedLabels:new Set(),labelFilters:{q:'',codigo_p:'',genero:'',dewey:''},filterOptions:{generos:[],codigos:[],idiomas:[]}};
s.book=id=>s.data.books.find(b=>b.id===Number(id));
s.filteredBooks=list=>sortBooks(s.data.books.filter(b=>!b.eliminado&&b.lista===list&&u.matchesSearch(b,s.filters.q)&&['genero','codigo_p','idioma','estado_lectura'].every(k=>!s.filters[k]||b[k]===s.filters[k])&&(!s.filters.favorito||b.favorito)),s.sortKey,s.sortDirection,s.data.loans);
s.labelFilteredBooks=()=>s.data.books.filter(b=>!b.eliminado&&b.lista==='catalogo'&&u.matchesSearch(b,s.labelFilters.q)&&(!s.labelFilters.codigo_p||b.codigo_p===s.labelFilters.codigo_p)&&(!s.labelFilters.genero||b.genero===s.labelFilters.genero)&&String(b.dewey||'').startsWith(s.labelFilters.dewey||''));
function postHost(payload){if(!embedded||window.parent===window)return;window.parent.postMessage({source:'habits-library',...payload},location.origin);}
function activeLibrary(){return s.libraries?.find(l=>l.activa)||null;}
function notifyHostContext(){const active=activeLibrary();postHost({type:'context',name:active?.nombre||s.config?.nombre_biblioteca||'Mi biblioteca',role:active?.rol||'',own:!!active?.propia,canWrite:!!s.canWrite});}
function applyHostAppearance(message){if(!embedded||message?.source!=='habits-shell'||message.type!=='appearance')return;document.documentElement.dataset.habitsTheme=message.theme==='dark'?'dark':'light';document.documentElement.classList.toggle('habits-large',!!message.large);document.documentElement.classList.toggle('habits-quiet',!!message.quiet);}
if(embedded&&window.parent!==window){window.addEventListener('message',event=>{if(event.origin===location.origin&&event.source===window.parent)applyHostAppearance(event.data);});const report=()=>requestAnimationFrame(()=>postHost({type:'resize',height:Math.ceil(root.scrollHeight+12)}));new ResizeObserver(report).observe(root);window.addEventListener('load',()=>{postHost({type:'ready'});report();},{once:true});}
const pageSizes=['12','24','48','100','200','500','todos'];
function pageSizeKey(){return `habits:library-page-size:${s.user?.id}:${libraryOwner}`;}
function readPageSize(){try{const value=localStorage.getItem(pageSizeKey());if(pageSizes.includes(value))return value;}catch{}return '24';}
root.addEventListener('change',e=>{if(!e.target.matches('[data-page-size]'))return;const value=e.target.value;if(!pageSizes.includes(value))return;try{localStorage.setItem(pageSizeKey(),value);}catch{}s.pageSize=value;s.perPage=value==='todos'?Math.max(1,s.data.books.length):Number(value);s.page=1;render();});
function toast(message){const t=document.querySelector('#library-toast');t.textContent=message;t.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.style.display='none',6500);}
function dialog(title,body,save,onSaved){
 const page=body.includes('class="book-editor"')||body.includes('library-book-detail-hero');
 if(modal.open)modal.close();modal.flushChanges=null;
 modal.classList.toggle('library-book-page',page);
 modal.innerHTML=`<div class="modal-heading library-modal-heading"><h2>${u.esc(title)}</h2><button type="button" class="button outline" data-action="close">Cerrar</button></div>${save?'<form>':''}${body}${save?'<div class="modal-footer"><button class="button primary" type="submit">Guardar</button></div></form>':''}`;if(page){if(body.includes('data-original-add')){modal.querySelector('form').classList.add('formulario','original-add-form');const intro=document.createElement('p');intro.className='nota';intro.textContent='Primero cargá título, autor y propietario. El número del propietario se asigna solo cuando el libro entra al catálogo real.';modal.querySelector('form').before(intro);}modal.show();modal.scrollIntoView({block:'start'});modal.querySelector('input,button')?.focus({preventScroll:true});}else modal.showModal();if(save)modal.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{if(await save(new FormData(e.target))===false)return;modal.close();await reload();window.dispatchEvent(new CustomEvent('habits:library-data-changed'));toast('Guardado.');onSaved?.();}catch(error){toast(error.message);}finally{b.disabled=false;}};}
async function loadSharing(){const l=await supabase.rpc('biblioteca_disponibles');s.libraries=l.error?[]:l.data||[];const manage=await supabase.rpc('biblioteca_can_manage');s.canManage=manage.error?false:manage.data===true;if(s.canManage){const m=await supabase.rpc('biblioteca_miembros');s.members=m.error?[]:m.data||[];}else s.members=[];notifyHostContext();}
let libraryChannel=null,remoteReloadTimer=null;
function stopLibraryRealtime(){if(libraryChannel){supabase.removeChannel(libraryChannel);libraryChannel=null;}clearTimeout(remoteReloadTimer);}
function startLibraryRealtime(){
 stopLibraryRealtime();
 if(!s.user||!libraryOwner)return;
 const owner=libraryOwner;
 const refresh=()=>{clearTimeout(remoteReloadTimer);remoteReloadTimer=setTimeout(async()=>{if(owner!==libraryOwner)return;try{data.invalidateLibraryData();await reload({force:true});window.dispatchEvent(new CustomEvent('habits:library-data-changed'));}catch(error){toast('No pude actualizar un cambio de otro dispositivo. Tocá Actualizar.');}},350);};
 libraryChannel=supabase.channel('biblioteca:'+owner);
 for(const table of ['biblioteca_libros','biblioteca_lecturas','biblioteca_lecturas_finalizadas','biblioteca_personas','biblioteca_prestamos','biblioteca_config']){
  libraryChannel.on('postgres_changes',{event:'*',schema:'public',table,filter:`owner_id=eq.${owner}`},refresh);
 }
 libraryChannel.subscribe();
}
async function reload({paint=true,force=false}={}){const access=await sessionAndAccess();if(!access.allowed||access.user?.id!==s.user?.id)throw new Error('Tu sesión o acceso cambió. Volvé a abrir Biblioteca.');await loadSharing();s.data=await data.loadAll({force});s.covers=await data.signedCoverMap(s.data.books);s.config=u.configObject(s.data.config);s.pageSize=readPageSize();s.perPage=s.pageSize==='todos'?Math.max(1,s.data.books.length):Number(s.pageSize);s.filterOptions={generos:u.unique(s.data.books.map(b=>b.genero)),codigos:u.unique(s.data.books.map(b=>b.codigo_p)),idiomas:u.unique(s.data.books.map(b=>b.idioma))};u.applyConfig(s.config);if(paint)render();}
function extraView(){if(s.view==='duplicados'){const groups=new Map();for(const b of s.data.books.filter(b=>!b.eliminado)){const key=u.cleanIsbn(b.isbn)||u.stripAccents(`${b.titulo}|${b.autor}`);groups.set(key,[...(groups.get(key)||[]),b]);}return `<h1>Posibles duplicados</h1><p>No se elimina ningún ejemplar automáticamente.</p>${[...groups.values()].filter(g=>g.length>1).map(g=>`<section class="lib-panel">${g.map(b=>button(u.esc(b.titulo)+' · '+u.esc(b.codigo_p||'')+' '+u.esc(b.item||''),'book',b.id)).join('')}</section>`).join('')||'<p>Sin coincidencias.</p>'}`;}if(s.view==='recomendador'){const available=s.data.books.filter(b=>!b.eliminado&&b.lista==='catalogo'&&b.estado_lectura==='no_leido'&&!s.data.loans.some(l=>l.libro_id===b.id&&l.activo));const recommended=available.sort((a,b)=>Number(b.proxima_lectura)-Number(a.proxima_lectura)||Number(b.favorito)-Number(a.favorito)||Number(a.paginas||9999)-Number(b.paginas||9999)).slice(0,12);return `<h1>Tu próxima lectura</h1><p>Libros disponibles sin leer, priorizando tu lista, favoritos y lecturas breves.</p>${recommended.map(b=>`<section class="lib-panel"><h3>${u.esc(b.titulo)}</h3><p>${u.esc(b.autor)} · ${b.paginas||'—'} páginas</p>${button('Ver ficha','book',b.id)}</section>`).join('')||'<p>No hay libros pendientes disponibles.</p>'}`;}return renderCurrentView(s);}
function render(){try{const prefs=JSON.parse(localStorage.getItem(pageSizeKey()+':layout')||'{}');s.columns=prefs.columns||DEFAULT_COLUMNS;s.sortKey=prefs.sortKey||'dewey';s.sortDirection=prefs.sortDirection||'asc';}catch{s.columns=DEFAULT_COLUMNS;}const assistantHost=root.querySelector('[data-assistant-host]');assistantHost?.remove();s.canWrite=canWrite;root.dataset.permission=canWrite?'write':'read';root.innerHTML=headerView(s)+`<main class="lib-main"><div class="lib-actions">${button('Actualizar','refresh-library')}${canWrite&&s.view==='catalogo'?button('Buscar por ISBN','isbn'):''}</div>${!canWrite?'<p class="lib-panel lib-readonly-note">👁️ Acceso de lectura. Podés consultar toda la biblioteca; los controles de edición están ocultos.</p>':''}${extraView()}</main>`;if(assistantHost)root.append(assistantHost);bindOriginalForms();const share=root.querySelector('#share-form');if(share)share.onsubmit=async e=>{e.preventDefault();const f=new FormData(share);const r=await supabase.rpc('biblioteca_invitar',{p_email:String(f.get('email')||''),p_rol:String(f.get('rol')||'reader')});if(r.error){toast(r.error.message);return;}await loadSharing();render();toast('Acceso actualizado. Los datos siguen perteneciendo a esta biblioteca.');};const config=root.querySelector('#config-form');if(config)config.onsubmit=async e=>{e.preventDefault();try{requireWrite();const f=new FormData(config);try{localStorage.setItem(pageSizeKey(),String(f.get('por_pagina')||'24'));}catch{}await data.saveConfig({...Object.fromEntries(f),mostrar_favoritos_catalogo:f.has('mostrar_favoritos_catalogo')?'1':'0'});await reload();toast('Configuración guardada.');}catch(error){toast(error.message);}};}
function requireWrite(){if(!canWrite)throw new Error('Tu permiso es de lectura. Pedí permiso de edición a la persona responsable.');}
function editBook(id,preset={}){
 requireWrite();if(id){bookDetail(id,true);return;}const book={...(s.book(id)||{}),...preset};let savedId=id,editor,draft=null;
 dialog(id?'Editar libro':'Agregar libro',(id?bookEditorHtml:newBookEditorHtml)(book,s.data.books),async f=>{
  const values=bookEditorValues(f,book);
  if(!savedId){const duplicate=s.data.books.find(x=>!x.eliminado&&((values.isbn&&u.cleanIsbn(x.isbn)===values.isbn)||u.stripAccents(x.titulo+'|'+(x.autor||''))===u.stripAccents(values.titulo+'|'+(values.autor||''))));if(duplicate&&!confirm(`Ya existe «${duplicate.titulo}». ¿Querés guardar otro ejemplar?`))return false;}
  if(savedId)await data.updateBook(savedId,values);else{const row=await data.insertBook({...values,estado_lectura:'no_leido',fecha_agregado:u.today()});savedId=row.id;}
  const chosen=editor.cover();
  try{if(chosen.file)await data.uploadCover(savedId,chosen.file);else if(chosen.changed)await data.replaceCover(savedId,chosen.url);}catch(error){throw new Error('El libro se guardó, pero falta la portada. Podés reintentar Guardar sin duplicarlo: '+error.message);}
  if(draft)await consumeDraft(draft.id);
 },()=>bookDetail(savedId));
 editor=bindBookEditor(modal.querySelector('form'),{book,cover:s.covers.get(id)});
 if(!id)bindDraftQr(modal.querySelector('form'),editor,row=>{draft=row;});else bindBookCoverQr(modal.querySelector('form'),id);
 if(!id){modal.querySelector('[type=submit]').textContent='Agregar libro';const cancel=document.createElement('button');cancel.type='button';cancel.className='button outline';cancel.dataset.action='close';cancel.textContent='Cancelar';modal.querySelector('.modal-footer').append(cancel);}
 modal.addEventListener('close',()=>editor.dispose(),{once:true});
}
function bookDetail(id,editing=false){
 const b=s.book(id);if(!b)return;editing=editing&&canWrite;
 const cover=s.covers.get(id),loan=s.data.loans.find(l=>l.libro_id===id&&l.activo);
 const tiles=[['dewey','Dewey'],['genero','Género'],['subdivision','Subdivisión'],['editorial','Editorial'],['paginas','Páginas'],['idioma','Idioma'],['estado_lectura','Estado']].filter(([k])=>['dewey','genero','estado_lectura'].includes(k)||b[k]);
 const actions=`<button type="button" class="volver" data-action="close">← Volver al catálogo</button><div class="ficha-acciones-superiores">${canWrite?`${button(editing?'👁 Ver ficha':'✏️ Editar',editing?'book':'edit-book',id)}${button(b.favorito?'⭐ Quitar favorito':'☆ Agregar favorito','favorite',id)}${b.lista!=='deseos'?`${button('📖 Estoy leyendo','reading-for-book',id)}${button('📚 Prestar este libro','loan-for-book',id)}${button(b.proxima_lectura?'Quitar de leer después':'📌 Quiero leer después',b.proxima_lectura?'remove-next':'add-next-book',id)}`:''}`:''}${loan?`<span class="chip chip-prestado">Prestado a ${u.esc(loan.persona)}</span>`:''}</div>`;
 const left=`<div class="ficha-portada">${cover?`<img class="original-book-cover" src="${u.esc(cover)}" alt="Portada de ${u.esc(b.titulo)}">`:`<div class="sin-portada grande">${u.esc(b.titulo)}</div>`}${editing?coverEditorHtml(b):''}${b.codigo_p||b.item?`<div class="dato-interno"><strong>Propietario:</strong> ${u.esc(b.codigo_p||'—')}${b.item?' · Nº '+u.esc(b.item):''}</div>`:''}</div>`;
 const read=`<h2>${u.esc(b.titulo)}</h2><p class="autor">${u.esc(b.autor||'')}</p>${starsHtml(b.rating)}<div class="ficha-resumen-grid">${tiles.map(([k,label])=>`<div><strong>${label}</strong><span>${k==='estado_lectura'?`<span class="chip chip-${b[k]}">${u.ESTADOS[b[k]]||'No leído'}</span>`:u.esc(k==='dewey'?u.deweyFmt(b[k])||'—':b[k]||'—')}</span></div>`).join('')}${b.autografiado?'<div><strong>Autografiado</strong><span>✍️ Sí</span></div>':''}</div>${b.paginas&&b.pagina_actual?`<div class="progreso"><div class="progreso-barra" style="width:${u.readingPercent(b)}%"></div><span>${u.readingPercent(b)}% · pág. ${b.pagina_actual} de ${b.paginas}</span></div>`:''}${[['descripcion','Sinopsis'],['dedicatoria','Dedicatoria / historia especial'],['relacionados','Libros relacionados'],['observaciones','Observaciones']].filter(([k])=>b[k]).map(([k,label])=>`<section class="bloque-lectura"><h3>${label}</h3><p>${u.esc(b[k])}</p></section>`).join('')}`;
 dialog(b.titulo,`<div class="library-book-detail-hero original-detail-page">${actions}${editing?'<section class="library-inline-editor"><form>':''}<div class="ficha ${editing?'modo-edicion':'modo-lectura'}">${left}<div class="ficha-datos">${editing?bookEditorHtml(b,s.data.books):read}${editing?`<p class="lib-autosave-status" role="status">Los cambios se guardan al salir de cada campo.</p><button type="button" data-retry-autosave hidden>Reintentar</button><button type="button" data-discard-autosave hidden>Descartar cambios no guardados y recargar</button><div class="original-delete">${button('🗑 Enviar a papelera','trash-book',id)}</div>`:''}</div></div>${editing?'</form></section>':''}<details class="original-history"><summary>Historial de este ejemplar</summary>${bookHistory(id,s)}<h3>Avances de lectura</h3>${s.data.readings.filter(r=>r.libro_id===id).map(r=>`<p>${u.fmtDate(r.fecha)} · página ${r.pagina} · ${r.paginas_leidas} páginas leídas</p>`).join('')||'<p>Sin registros.</p>'}</details></div>`);
 modal.querySelector('.library-modal-heading').hidden=true;
 if(editing)bindInlineEditor(b);
}
function selectBook(title,callback){requireWrite();dialog(title,`<label class="lib-field">Libro<select class="lib-select" name="book">${s.data.books.filter(b=>!b.eliminado&&b.lista==='catalogo').map(b=>`<option value="${b.id}">${u.esc(b.titulo)}</option>`).join('')}</select></label>`,f=>callback(Number(f.get('book'))));}
async function transition(kind,id,payload={}){requireWrite();const {error}=await supabase.rpc('biblioteca_transition',{p_action:kind,p_book:id,p_data:payload});if(error)throw error;data.invalidateLibraryData();}
async function action(a,el){const id=Number(el.dataset.id),b=s.book(id);if(a==='sort-column'||a==='sort-direction'){const key=el.dataset.key||s.sortKey;saveCatalogPreferences({sortKey:key,sortDirection:a==='sort-direction'||s.sortKey===key?(s.sortDirection==='desc'?'asc':'desc'):'asc'});return;}if(a==='stat-filter'){s.filters={q:el.dataset.query||'',genero:'',codigo_p:'',idioma:'',estado_lectura:'',favorito:false};s.view='catalogo';s.page=1;render();return;}if(a==='refresh-library'){data.invalidateLibraryData();await reload({force:true});await data.retryCoverCleanup();window.dispatchEvent(new CustomEvent('habits:library-data-changed'));return;}if(a==='close'){modal.close();return;}if(a==='lib-own'){const r=await supabase.rpc('biblioteca_elegir',{p_owner:s.user.id});if(r.error)throw r.error;data.clearLibraryCache();window.dispatchEvent(new CustomEvent('habits:library-context-changed'));await reload({force:true});return;}if(a==='share-leave'){if(!confirm('¿Salir de esta biblioteca compartida? Tu biblioteca personal no cambia.'))return;const r=await supabase.rpc('biblioteca_salir',{p_owner:el.dataset.owner});if(r.error)throw r.error;data.clearLibraryCache();window.dispatchEvent(new CustomEvent('habits:library-context-changed'));await reload({force:true});return;}if(a==='share-remove'){if(!confirm(`¿Quitarle el acceso a ${el.dataset.email}? Sus datos personales no se modifican.`))return;const r=await supabase.rpc('biblioteca_quitar_miembro',{p_user:el.dataset.user});if(r.error)throw r.error;await loadSharing();render();toast('Acceso quitado.');return;}if(a==='view'){modal.close();s.view=({listas:'deseos',mas:'revisar'})[el.dataset.view]||el.dataset.view;s.personHistory=null;s.page=1;render();return;}if(a==='book'){bookDetail(id);return;}if(a==='reading-for-book'||a==='loan-for-book'){s.selectedBook=id;s.view=a==='reading-for-book'?'lecturas':'prestamos';modal.close();render();return;}if(a==='duplicates'||a==='recommend'){s.view=a==='duplicates'?'duplicados':'recomendador';s.personHistory=null;render();return;}if(a==='person-history'){s.personHistory=el.dataset.person;render();return;}if(a==='apply-filters'){for(const [key,node] of Object.entries({q:'catalog-q',genero:'filter-genero',codigo_p:'filter-codigo',idioma:'filter-idioma',estado_lectura:'filter-estado'}))s.filters[key]=document.getElementById(node).value;s.page=1;render();return;}if(a==='clear-filters'){s.filters={q:'',genero:'',codigo_p:'',idioma:'',estado_lectura:'',favorito:false};s.page=1;render();return;}if(a==='toggle-favorites'){s.filters.favorito=!s.filters.favorito;render();return;}if(a==='toggle-view-mode'){s.viewMode=s.viewMode==='lista'?'cuadricula':'lista';render();return;}if(a==='page'){s.page=Number(el.dataset.page);render();root.querySelector('.lib-toolbar')?.scrollIntoView({block:'start'});return;}if(a==='review-filter'){s.reviewKey=el.dataset.key;render();return;}
 if(a.startsWith('label-')){const visible=s.labelFilteredBooks();if(a==='label-apply'){for(const [k,node] of Object.entries({q:'label-q',codigo_p:'label-owner',genero:'label-genre',dewey:'label-dewey'}))s.labelFilters[k]=document.getElementById(node).value;}if(a==='label-select-visible')visible.forEach(b=>s.selectedLabels.add(b.id));if(a==='label-unselect-visible')visible.forEach(b=>s.selectedLabels.delete(b.id));if(a==='label-select-all')s.data.books.filter(b=>!b.eliminado&&b.lista==='catalogo').forEach(b=>s.selectedLabels.add(b.id));if(a==='label-clear')s.selectedLabels.clear();render();return;}
 if(a==='print-labels'){const books=s.data.books.filter(b=>s.selectedLabels.has(b.id));if(!books.length)throw new Error('Seleccioná al menos un libro.');const {jsPDF}=await import('jspdf');const pdf=new jsPDF();books.forEach((b,i)=>{if(i&&i%60===0)pdf.addPage();const n=i%60,x=10+(n%6)*32,y=10+Math.floor(n/6)*27;pdf.rect(x,y,30,25);pdf.setFontSize(10);pdf.text([u.deweyFmt(b.dewey)||'SIN',u.cutterAuthor(b.autor),`${b.codigo_p||''}-${b.item||''}`],x+15,y+7,{align:'center',maxWidth:28});});pdf.save('etiquetas.pdf');return;}
 if(a==='export-json'){u.downloadBlob(`biblioteca-${u.today()}.json`,JSON.stringify({version:18,...s.data},null,2),'application/json');return;}if(a==='export-csv'){u.downloadBlob('biblioteca.csv',u.csvText(s.data.books,Object.keys(s.data.books[0]||{titulo:''})),'text/csv');return;}if(a==='download-backup'){const backup=await latestBackup();if(!backup)throw new Error('Todavía no hay respaldos. Podés exportar JSON ahora.');u.downloadBlob(backup.name,backup.blob);return;}
 requireWrite();
 if(a==='new-book'||a==='edit-book'){editBook(a==='edit-book'?id:null,{...(el.dataset.list?{lista:el.dataset.list}:{})});return;}
 if(a==='isbn'){dialog('Buscar por ISBN',field('isbn','ISBN','','text','required')+button('Escanear con cámara','scan-isbn'),async f=>{const result=await u.lookupIsbn(f.get('isbn'));setTimeout(()=>editBook(null,result),0);});return;}
 if(a==='scan-isbn'){const {BrowserMultiFormatReader}=await import('@zxing/browser');const reader=new BrowserMultiFormatReader();const video=document.createElement('video');video.style.maxWidth='100%';modal.append(video);let controls;const stop=()=>{controls?.stop();video.remove();};modal.addEventListener('close',stop,{once:true});controls=await reader.decodeFromVideoDevice(undefined,video,(result)=>{if(result){const input=modal.querySelector('[name=isbn]');if(input)input.value=u.cleanIsbn(result.getText());stop();}});return;}
 if(a==='start-reading'){dialog('Empezar una lectura',`<label class="lib-field">Libro<select name="book" class="lib-select">${s.data.books.filter(b=>!b.eliminado&&b.lista==='catalogo').map(b=>`<option value="${b.id}">${u.esc(b.titulo)}</option>`).join('')}</select></label>`+field('start','Fecha de inicio',u.today(),'date','required'),f=>transition('start',Number(f.get('book')),{start:f.get('start')}));return;}if(a==='add-next'){selectBook('Agregar a próximas lecturas',id=>data.updateBook(id,{proxima_lectura:true}));return;}
 if(a==='update-page'){dialog('Actualizar página',field('page','Página actual',b.pagina_actual||0,'number',`required min="0" ${b.paginas?'max="'+b.paginas+'"':''}`),f=>transition('page',id,{page:Number(f.get('page'))}));return;}
 if(a==='finish-reading'){dialog('Concluir lectura',field('start','Fecha de inicio',b.fecha_inicio||u.today(),'date','required')+field('end','Fecha de finalización',u.today(),'date','required')+field('rating','Mi puntuación (1 a 10)',b.rating||'','number','min="1" max="10" step="1"')+text('comment','Comentario'),f=>transition('finish',id,{start:f.get('start'),end:f.get('end'),rating:f.get('rating')||null,comment:f.get('comment')}));return;}
 if(a==='abandon-reading'){dialog('Abandonar lectura','<p>El historial anterior se conserva.</p>',()=>transition('abandon',id));return;}
 if(a==='cover'){dialog('Subir portada',field('image','Imagen','','file','accept="image/jpeg,image/png,image/webp" required'),f=>data.uploadCover(id,f.get('image')));return;}
 if(a==='phone-cover'){const url=new URL('biblioteca.html',location.href);url.searchParams.set('cover',id);url.searchParams.set('owner',libraryOwner);const {default:QR}=await import('qrcode');const qr=await QR.toDataURL(url.href);dialog('Cargar desde el celular',`<p>Abrí este enlace en tu celular e iniciá sesión con una cuenta autorizada. El permiso se verifica antes de aceptar la imagen.</p><img src="${qr}" alt="Código QR del libro"><p><a href="${u.esc(url.href)}">Abrir carga de portada</a></p>`);return;}
 if(a==='internet'){toast('Buscando datos…');const options=await u.internetOptions(b.titulo,b.autor);dialog('Elegí la información',options.map((o,i)=>`<section class="lib-panel"><h3>${u.esc(o.titulo)}</h3><p>${u.esc(o.autor)} · ${u.esc(o.fuente)}</p><p>${u.esc(o.descripcion)}</p>${o.portada_url?`<img src="${u.esc(o.portada_url)}" alt="Portada propuesta" style="max-width:100px">`:''}${button('Completar campos vacíos','apply-option',i)}</section>`).join('')||'<p>No se encontraron resultados.</p>');modal.options=options;modal.bookId=id;return;}
 if(a==='apply-option'){const option=modal.options[id],book=s.book(modal.bookId),patch={};for(const k of ['titulo','autor','editorial','paginas','isbn','idioma','descripcion'])if(!book[k]&&option[k])patch[k]=option[k];if(!book.portada&&option.portada_url)patch.portada=option.portada_url;await data.updateBook(book.id,patch);}
 else if(a==='new-loan'){dialog('Registrar préstamo',`<label class="lib-field">Libro<select name="book" class="lib-select">${s.data.books.filter(b=>!b.eliminado&&b.lista==='catalogo'&&!s.data.loans.some(l=>l.libro_id===b.id&&l.activo)).map(b=>`<option value="${b.id}">${u.esc(b.titulo)}</option>`).join('')}</select></label>`+field('person','Persona','','text','required')+field('date','Fecha del préstamo',u.today(),'date','required')+field('due','Devolución prevista','','date')+text('notes','Notas'),f=>transition('loan',Number(f.get('book')),{person:f.get('person'),date:f.get('date'),due:f.get('due')||null,notes:f.get('notes')}));return;}
 else if(a==='return-loan'||a==='lost-loan'){const loan=s.data.loans.find(l=>l.id===id);dialog(a==='return-loan'?'Registrar devolución':'Marcar perdido',text('condition','Estado / observaciones'),f=>transition(a==='return-loan'?'return':'lost',loan.libro_id,{loan:id,condition:f.get('condition')}));return;}
 else if(a==='delete-loan'||a==='delete-forever'||a==='empty-trash'){dialog('Confirmar eliminación definitiva','<p>Esta acción no se puede deshacer. Exportá una copia si querés conservar el historial.</p>',async()=>{if(a==='delete-loan')await data.deleteLoan(id);else if(a==='delete-forever')await data.deleteBookForever(id);else for(const book of s.data.books.filter(b=>b.eliminado))await data.deleteBookForever(book.id);});return;}
 else if(a==='start-book'){startReadingDialog(id);return;}
 else if(a==='favorite')await data.updateBook(id,{favorito:!b.favorito});
 else if(a==='add-next-book'||a==='remove-next')await data.updateBook(id,{proxima_lectura:a==='add-next-book'});
 else if(a==='buy-book')await data.updateBook(id,{lista:'catalogo',fecha_agregado:u.today()});
 else if(a==='trash-book')await data.deleteBookSoft(id);
 else if(a==='restore-book')await data.restoreBook(id);
 else if(a==='remove-cover')await data.replaceCover(id,null);
 else throw new Error('No se pudo identificar la acción.');
 modal.close();await reload();window.dispatchEvent(new CustomEvent('habits:library-data-changed'));toast('Guardado.');
}
window.addEventListener('habits:library-open-book',event=>{const id=Number(event.detail?.id);if(id&&s.book(id))bookDetail(id);});
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el||!(root?.contains(el)||modal?.contains(el)))return;e.preventDefault();el.disabled=true;try{if(modal.flushChanges)await modal.flushChanges();await action(el.dataset.action,el);}catch(error){toast(error.message);}finally{el.disabled=false;}});
document.addEventListener('change',e=>{if(e.target.dataset.labelId){const id=Number(e.target.dataset.labelId);e.target.checked?s.selectedLabels.add(id):s.selectedLabels.delete(id);render();}});
let disposeAssistant=()=>{};
async function initLibrary(){disposeAssistant();root.querySelector('[data-assistant-host]')?.remove();try{let access=await sessionAndAccess();const requestedOwner=params.get('draft')||params.get('cover')?params.get('owner'):null;if(access.user&&requestedOwner&&requestedOwner!==access.owner){const switched=await supabase.rpc('biblioteca_elegir',{p_owner:requestedOwner});if(switched.error)throw switched.error;access=await sessionAndAccess();}if(!access.user){root.innerHTML='<main class="lib-main"><h1>Tu biblioteca privada</h1><p>Iniciá sesión en Habits para continuar.</p><a href="./">Ir a Habits</a></main>';}else if(!access.allowed){root.innerHTML='<main class="lib-main"><h1>Biblioteca con acceso restringido</h1><p>Esta cuenta no está autorizada. Tus hábitos, diario y calendario siguen disponibles.</p><a href="./">Volver a Habits</a></main>';}else{s.user=access.user;await ensureConfig();await reload();startLibraryRealtime();s.viewMode=s.config.vista_default||'cuadricula';render();const assistantHost=document.createElement('div');assistantHost.dataset.assistantHost='';root.append(assistantHost);disposeAssistant=mountLibraryAssistant(assistantHost,{getSnapshot:async()=>{const access=await sessionAndAccess();if(!access.allowed||access.user?.id!==s.user?.id)throw new Error('Tu sesión cambió. Volvé a abrir Biblioteca.');const active=s.libraries?.find(l=>l.activa);if(active&&access.owner!==active.owner_id)throw new Error('La biblioteca activa cambió en otra ventana. Recargá para consultar el catálogo correcto.');await reload({paint:false});return {...s.data,library:s.libraries?.find(l=>l.activa)||{nombre:s.config.nombre_biblioteca}};}});if(canWrite)createDailyBackup(s.data).catch(()=>toast('No se pudo crear el respaldo diario. Podés exportar JSON desde Configuración.'));const draftId=new URL(location.href).searchParams.get('draft');if(draftId&&canWrite)await openDraftUpload(draftId);const bookId=Number(new URL(location.href).searchParams.get('cover'));if(bookId&&s.book(bookId)&&canWrite)await action('cover',{dataset:{id:bookId}});}}catch(error){root.innerHTML=`<main class="lib-main"><h1>No se pudo abrir la biblioteca</h1><p>${u.esc(error.message)}</p><p>Revisá la conexión y que las migraciones de Biblioteca estén aplicadas.</p><a href="./">Volver a Habits</a></main>`;}}
let initializing=initLibrary();
supabase.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'&&session?.user?.id!==s.user?.id){setTimeout(()=>{initializing=initializing.catch(()=>{}).then(()=>session.user.id!==s.user?.id?initLibrary():undefined);},0);}if(event==='SIGNED_OUT'){disposeAssistant();stopLibraryRealtime();resetLibraryContext();data.clearLibraryCache();window.dispatchEvent(new CustomEvent('habits:library-context-changed'));s.user=null;document.querySelector('[data-assistant-host]')?.remove();s.data={books:[],loans:[],readings:[],finished:[],people:[],config:[]};s.covers.clear();modal.close();root.innerHTML='<main class="lib-main"><p>Sesión cerrada.</p><a href="./">Volver a Habits</a></main>';}});

// Cambiar de biblioteca cambia el contexto activo: nunca copia ni mezcla datos.
document.addEventListener('change',async e=>{const sel=e.target.closest?.('[data-lib-switch]');if(!sel)return;sel.disabled=true;const r=await supabase.rpc('biblioteca_elegir',{p_owner:sel.value});if(r.error){toast(r.error.message);sel.disabled=false;return;}data.clearLibraryCache();window.dispatchEvent(new CustomEvent('habits:library-context-changed'));await reload({force:true});startLibraryRealtime();});

window.addEventListener('library:cleanup-warning',()=>setTimeout(()=>toast('Guardado. Quedó una portada anterior por limpiar; tocá Actualizar cuando haya conexión.'),0));

function saveCatalogPreferences(patch){const prefs={columns:s.columns||DEFAULT_COLUMNS,sortKey:s.sortKey||'dewey',sortDirection:s.sortDirection||'asc',...patch};localStorage.setItem(pageSizeKey()+':layout',JSON.stringify(prefs));Object.assign(s,prefs);s.page=1;render();}
root.addEventListener('change',e=>{const col=e.target.dataset.libraryColumn;if(col&&COLUMNS[col]){const columns=new Set(s.columns||DEFAULT_COLUMNS);e.target.checked?columns.add(col):columns.delete(col);saveCatalogPreferences({columns:[...columns]});}if(e.target.matches('[data-library-sort]'))saveCatalogPreferences({sortKey:e.target.value});});

function startReadingDialog(id){dialog('Empezar lectura',field('start','Fecha de inicio',u.today(),'date','required'),f=>transition('start',id,{start:f.get('start')}));}

function bindInlineEditor(book){
 const form=modal.querySelector('.library-inline-editor form'),status=modal.querySelector('.lib-autosave-status'),retry=modal.querySelector('[data-retry-autosave]'),owner=libraryOwner;let validationError=false;const discard=modal.querySelector('[data-discard-autosave]');
 const editor=bindBookEditor(form,{book,cover:s.covers.get(book.id)});bindBookCoverQr(form,book.id);
 const auto=createAutosave(async(name,value)=>{if(owner!==libraryOwner||!canWrite)throw new Error('La biblioteca o tus permisos cambiaron.');if(name==='cover'){if(value.file)await data.uploadCover(book.id,value.file);else await data.replaceCover(book.id,value.url);}else if(name==='pagina_actual'){await transition('page',book.id,{page:value});book.pagina_actual=value;}else {const patch={[name]:value};if(name==='dewey')patch.dewey_orden=u.deweyNumber(value);const row=await data.updateBook(book.id,patch,{[name]:book[name]});Object.assign(book,row);}window.dispatchEvent(new CustomEvent('habits:library-data-changed'));},(text,error)=>{status.textContent=text;status.classList.toggle('error',error);retry.hidden=!error;discard.hidden=!error;});
 retry.onclick=()=>auto.retry();discard.onclick=async()=>{if(!confirm('¿Descartar solamente los cambios que no se guardaron y cargar la ficha actual?'))return;await auto.discard();await reload({force:true});bookDetail(book.id);};modal.flushChanges=()=>{if(validationError)throw new Error('Corregí el campo indicado antes de cerrar.');return auto.flush();};
 form.onsubmit=e=>{e.preventDefault();auto.retry();};
 form.addEventListener('change',e=>{try{if(e.target.name==='coverUrl'||e.target.matches('[data-cover-file]')){auto.enqueue('cover',editor.cover());return;}const values=bookEditorValues(new FormData(form),book),name=e.target.name;if(name==='estado_lectura')values.estado_lectura=e.target.value;if(name==='pagina_actual'){const page=Number(e.target.value);if(!Number.isInteger(page)||page<0||(book.paginas&&page>book.paginas))throw new Error('Indicá una página válida dentro del libro.');values.pagina_actual=page;}validationError=false;if(Object.hasOwn(values,name))auto.enqueue(name,values[name]);}catch(error){validationError=true;status.textContent=error.message;status.classList.add('error');}});
 form.addEventListener('editor-cover-changed',()=>auto.enqueue('cover',editor.cover()));
 const warn=e=>{if(auto.pending||validationError){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);
 modal.addEventListener('close',()=>{editor.dispose();window.removeEventListener('beforeunload',warn);},{once:true});
}

function bindDraftQr(form,editor,onDraft){
 const box=document.createElement('section');box.className='lib-draft-qr qr-foto';box.innerHTML='<strong>Subir portada desde el celular</strong><button type="button" class="lib-button secondary">Subir portada desde otro celular (QR)</button><p role="status"></p><div></div>';form.querySelector('[data-qr-slot]').append(box);
 let timer=null,stopped=false,last='',draft;const owner=libraryOwner;
 box.querySelector('button').onclick=async()=>{const status=box.querySelector('p');try{if(draft&&Date.parse(draft.expires_at)<=Date.now())draft=null;draft??=await createDraft();onDraft(draft);const url=new URL('./',location.href);url.hash='/library';url.searchParams.set('draft',draft.id);url.searchParams.set('owner',owner);const {default:QR}=await import('qrcode');const img=document.createElement('img');img.alt='Escaneá para subir la portada';img.src=await QR.toDataURL(url.href);const link=document.createElement('a');link.href=url.href;link.textContent='Abrir enlace';box.querySelector('div').replaceChildren(img,link);box.querySelector('button').hidden=true;status.textContent='Válido por una hora. En el celular iniciá sesión con permiso de edición en esta biblioteca.';
 const poll=async()=>{if(stopped||!form.isConnected||owner!==libraryOwner)return;try{const row=await readDraft(draft.id);if(row.uploaded_at&&row.uploaded_at!==last){last=row.uploaded_at;editor.chooseStoredCover(draftPath(owner,row.id),await draftPreview(row));status.textContent='Portada recibida. Guardá el libro para conservarla.';}timer=setTimeout(poll,5000);}catch(error){status.textContent=error.message;}};clearTimeout(timer);await poll();
 }catch(error){status.textContent=error.message;}};
 form.addEventListener('cover-window-open',()=>{if(!draft||Date.parse(draft.expires_at)<=Date.now())box.querySelector('button').click();});
 modal.addEventListener('close',()=>{stopped=true;clearTimeout(timer);},{once:true});
}
async function openDraftUpload(id){requireWrite();const row=await readDraft(id);dialog('Portada para el libro nuevo','<p>La imagen llegará al formulario abierto en la notebook. No se crea ningún libro hasta que lo guardes allí.</p>'+field('photo','Foto de portada','','file','accept="image/jpeg,image/png,image/webp" required'),async f=>{await uploadDraft(row.id,f.get('photo'));toast('Portada enviada a la notebook.');});}

function bindBookCoverQr(form,id){
 const box=document.createElement('section');box.className='lib-draft-qr qr-foto';box.innerHTML='<strong>Subir portada desde el celular</strong><button type="button" class="lib-button secondary">Subir portada desde otro celular (QR)</button><p role="status"></p><div></div>';form.querySelector('[data-qr-slot]').append(box);
 box.querySelector('button').onclick=async()=>{try{const url=new URL('biblioteca.html',location.href);url.searchParams.set('cover',id);url.searchParams.set('owner',libraryOwner);const {default:QR}=await import('qrcode');const img=document.createElement('img');img.alt='Escaneá para subir la portada';img.src=await QR.toDataURL(url.href);const link=document.createElement('a');link.href=url.href;link.textContent='Abrir carga de portada';box.querySelector('div').replaceChildren(img,link);box.querySelector('button').hidden=true;box.querySelector('p').textContent='Escaneá el QR y subí una foto con una cuenta autorizada. Se guarda en este libro.';}catch(error){box.querySelector('p').textContent=error.message;}};
 form.addEventListener('cover-window-open',()=>{if(!box.querySelector('img'))box.querySelector('button').click();});
}

function bindOriginalForms(){
 root.querySelectorAll('form[data-transition]').forEach(form=>form.onsubmit=async e=>{
 e.preventDefault();const submit=e.submitter;submit.disabled=true;const status=form.querySelector('[role=status]');
 try{requireWrite();const f=new FormData(form),kind=form.dataset.transition;let id=Number(form.dataset.book);
 if(!id){const query=String(f.get('book')||'').trim(),exact=s.data.books.filter(b=>!b.eliminado&&b.lista==='catalogo').filter(b=>bookOption(b)===query||u.stripAccents(b.titulo)===u.stripAccents(query));const matches=exact.length?exact:s.data.books.filter(b=>!b.eliminado&&b.lista==='catalogo'&&u.matchesSearch(b,query));if(matches.length!==1)throw new Error(matches.length?'Hay varios ejemplares: elegí uno de la lista.':'Elegí un libro del catálogo.');id=matches[0].id;}
 const payload=kind==='start'?{start:f.get('start')}:kind==='page'?{page:Number(f.get('page'))}:kind==='finish'?{start:f.get('start'),end:f.get('end'),rating:f.get('rating')||null,comment:f.get('comment')}:kind==='loan'?{person:f.get('person'),date:f.get('date'),due:f.get('due')||null,notes:f.get('notes')}:{loan:Number(form.dataset.loan),condition:f.get('condition')};
 if(kind==='abandon'&&!confirm('¿Marcar como abandonado? El historial se conserva.'))return;
 await transition(kind,id,payload);await reload();window.dispatchEvent(new CustomEvent('habits:library-data-changed'));toast('Guardado.');
 }catch(error){if(status)status.textContent=error.message;else toast(error.message);}finally{submit.disabled=false;}
 });
 root.querySelectorAll('[data-rating]').forEach(btn=>btn.onclick=()=>{const group=btn.closest('.estrellas');group.querySelector('[name=rating]').value=btn.dataset.rating;group.querySelector('[data-rating-text]').textContent=btn.dataset.rating+'/10';group.querySelectorAll('[data-rating]').forEach(x=>{x.classList.toggle('llena',Number(x.dataset.rating)<=Number(btn.dataset.rating));x.setAttribute('aria-pressed',String(x===btn));});});
}
function bookOption(b){return `${b.titulo} — ${b.autor||'Sin autor'} · ${b.codigo_p||'Sin código'} Nº ${b.item||b.id}`;}
