import './biblioteca.css';
import {supabase,sessionAndAccess,ensureConfig,canWrite} from './biblioteca/client.js';
import * as data from './biblioteca/data.js';
import * as u from './biblioteca/utils.js';
import {headerView,renderCurrentView} from './biblioteca/views.js';
import {createDailyBackup,latestBackup} from './biblioteca/backups.js';
const root=document.querySelector('#library-app'),modal=document.querySelector('#library-modal');
const button=(label,action,id='')=>`<button type="button" class="lib-button secondary" data-action="${action}" data-id="${id}">${label}</button>`;
const field=(name,label,value='',type='text',extra='')=>`<label class="lib-field">${label}<input class="lib-input" name="${name}" type="${type}" value="${u.esc(value??'')}" ${extra}></label>`;
const text=(name,label,value='')=>`<label class="lib-field">${label}<textarea class="lib-input" name="${name}" rows="4">${u.esc(value??'')}</textarea></label>`;
const s={user:null,data:{books:[],readings:[],finished:[],people:[],loans:[],config:[]},config:u.DEFAULT_CONFIG,covers:new Map(),view:'catalogo',page:1,perPage:200,viewMode:'cuadricula',reviewKey:'all',personHistory:null,filters:{q:'',genero:'',codigo_p:'',idioma:'',estado_lectura:'',favorito:false},selectedLabels:new Set(),labelFilters:{q:'',codigo_p:'',genero:'',dewey:''},filterOptions:{generos:[],codigos:[],idiomas:[]}};
s.book=id=>s.data.books.find(b=>b.id===Number(id));
s.filteredBooks=list=>s.data.books.filter(b=>!b.eliminado&&b.lista===list&&u.matchesSearch(b,s.filters.q)&&['genero','codigo_p','idioma','estado_lectura'].every(k=>!s.filters[k]||b[k]===s.filters[k])&&(!s.filters.favorito||b.favorito)).sort((a,b)=>(u.deweyNumber(a.dewey)??Infinity)-(u.deweyNumber(b.dewey)??Infinity)||String(a.titulo).localeCompare(b.titulo,'es'));
s.labelFilteredBooks=()=>s.data.books.filter(b=>!b.eliminado&&b.lista==='catalogo'&&u.matchesSearch(b,s.labelFilters.q)&&(!s.labelFilters.codigo_p||b.codigo_p===s.labelFilters.codigo_p)&&(!s.labelFilters.genero||b.genero===s.labelFilters.genero)&&String(b.dewey||'').startsWith(s.labelFilters.dewey||''));
function toast(message){const t=document.querySelector('#library-toast');t.textContent=message;t.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.style.display='none',6500);}
function dialog(title,body,save){modal.innerHTML=`<div class="lib-page-head"><h2>${u.esc(title)}</h2>${button('Cerrar','close')}</div>${save?'<form>':''}${body}${save?'<button class="lib-button" type="submit">Guardar</button></form>':''}`;if(!modal.open)modal.showModal();if(save)modal.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await save(new FormData(e.target));modal.close();await reload();toast('Guardado.');}catch(error){toast(error.message);}finally{b.disabled=false;}};}
async function reload(){s.data=await data.loadAll();s.covers=await data.signedCoverMap(s.data.books);s.config=u.configObject(s.data.config);s.perPage=s.config.por_pagina==='todos'?Math.max(1,s.data.books.length):Math.max(1,Number(s.config.por_pagina)||200);s.filterOptions={generos:u.unique(s.data.books.map(b=>b.genero)),codigos:u.unique(s.data.books.map(b=>b.codigo_p)),idiomas:u.unique(s.data.books.map(b=>b.idioma))};u.applyConfig(s.config);render();}
function extraView(){if(s.view==='duplicados'){const groups=new Map();for(const b of s.data.books.filter(b=>!b.eliminado)){const key=u.cleanIsbn(b.isbn)||u.stripAccents(`${b.titulo}|${b.autor}`);groups.set(key,[...(groups.get(key)||[]),b]);}return `<h1>Posibles duplicados</h1><p>No se elimina ningún ejemplar automáticamente.</p>${[...groups.values()].filter(g=>g.length>1).map(g=>`<section class="lib-panel">${g.map(b=>button(u.esc(b.titulo)+' · '+u.esc(b.codigo_p||'')+' '+u.esc(b.item||''),'book',b.id)).join('')}</section>`).join('')||'<p>Sin coincidencias.</p>'}`;}if(s.view==='recomendador'){const available=s.data.books.filter(b=>!b.eliminado&&b.lista==='catalogo'&&b.estado_lectura==='no_leido'&&!s.data.loans.some(l=>l.libro_id===b.id&&l.activo));const recommended=available.sort((a,b)=>Number(b.proxima_lectura)-Number(a.proxima_lectura)||Number(b.favorito)-Number(a.favorito)||Number(a.paginas||9999)-Number(b.paginas||9999)).slice(0,12);return `<h1>Tu próxima lectura</h1><p>Libros disponibles sin leer, priorizando tu lista, favoritos y lecturas breves.</p>${recommended.map(b=>`<section class="lib-panel"><h3>${u.esc(b.titulo)}</h3><p>${u.esc(b.autor)} · ${b.paginas||'—'} páginas</p>${button('Ver ficha','book',b.id)}</section>`).join('')||'<p>No hay libros pendientes disponibles.</p>'}`;}return renderCurrentView(s);}
function render(){root.innerHTML=headerView(s)+`<main class="lib-main"><div class="lib-actions">${button('Duplicados','duplicates')}${button('Recomendador','recommend')}${canWrite?button('Buscar por ISBN','isbn'):''}</div>${!canWrite?'<p class="lib-panel">Acceso de lectura. Solo las personas con permiso de edición pueden modificar esta biblioteca.</p>':''}${extraView()}</main>`;const config=root.querySelector('#config-form');if(config)config.onsubmit=async e=>{e.preventDefault();try{requireWrite();const f=new FormData(config);await data.saveConfig({...Object.fromEntries(f),mostrar_favoritos_catalogo:f.has('mostrar_favoritos_catalogo')?'1':'0'});await reload();toast('Configuración guardada.');}catch(error){toast(error.message);}};}
function requireWrite(){if(!canWrite)throw new Error('Tu permiso es de lectura. Pedí permiso de edición a la persona responsable.');}
function editBook(id,preset={}){requireWrite();const b={...(s.book(id)||{}),...preset};const names={titulo:'Título',autor:'Autor',codigo_p:'Código de propietario',item:'Número de ejemplar',dewey:'Dewey',genero:'Género',subdivision:'Subdivisión',editorial:'Editorial',paginas:'Páginas',isbn:'ISBN',idioma:'Idioma',relacionados:'Libros relacionados'};dialog(id?'Editar libro':'Agregar libro',Object.entries(names).map(([k,label])=>field(k,label,b[k],['item','paginas'].includes(k)?'number':'text',k==='titulo'?'required':(['item','paginas'].includes(k)?'min="0"':''))).join('')+`<label class="lib-field">Lista<select name="lista" class="lib-select"><option value="catalogo">Catálogo</option><option value="deseos" ${b.lista==='deseos'?'selected':''}>Deseos</option></select></label>`+text('descripcion','Sinopsis',b.descripcion)+text('observaciones','Observaciones',b.observaciones)+text('dedicatoria','Dedicatoria',b.dedicatoria)+field('rating','Valoración (0 a 5)',b.rating||0,'number','min="0" max="5"')+`<label><input type="checkbox" name="autografiado" ${b.autografiado?'checked':''}> Autografiado</label>`,async f=>{const v=Object.fromEntries(f);v.paginas=v.paginas?Number(v.paginas):null;v.item=v.item?Number(v.item):null;v.rating=Number(v.rating);v.autografiado=f.has('autografiado');v.dewey_orden=u.deweyNumber(v.dewey);if(id)await data.updateBook(id,v);else await data.insertBook({...v,estado_lectura:'no_leido',fecha_agregado:u.today(),portada:b.portada_url||null});});}
function bookDetail(id){const b=s.book(id);if(!b)return;dialog(b.titulo,`${s.covers.has(b.id)?`<img src="${u.esc(s.covers.get(b.id))}" alt="Portada" style="max-width:180px">`:''}<p>${u.esc(b.autor)}</p><p>${u.esc(b.descripcion||'Sin sinopsis')}</p><dl>${Object.entries(b).filter(([k,v])=>!['id','owner_id','portada','descripcion'].includes(k)&&v!==null).map(([k,v])=>`<dt>${u.esc(k)}</dt><dd>${u.esc(v)}</dd>`).join('')}</dl><div class="lib-actions">${canWrite?['edit-book','favorite','start-book','add-next-book','cover','remove-cover','internet','phone-cover','trash-book'].map((a,i)=>button(['Editar','Favorito ☆','Empezar lectura','Leer después','Subir / cambiar portada','Quitar portada','Buscar datos y portadas','Cargar desde celular','Enviar a papelera'][i],a,id)).join(''):''}</div><h3>Historial de lectura</h3>${s.data.readings.filter(r=>r.libro_id===id).map(r=>`<p>${u.esc(r.fecha)} · página ${r.pagina} · ${r.paginas_leidas} páginas leídas</p>`).join('')||'<p>Sin registros.</p>'}`);}
function selectBook(title,callback){requireWrite();dialog(title,`<label class="lib-field">Libro<select class="lib-select" name="book">${s.data.books.filter(b=>!b.eliminado&&b.lista==='catalogo').map(b=>`<option value="${b.id}">${u.esc(b.titulo)}</option>`).join('')}</select></label>`,f=>callback(Number(f.get('book'))));}
async function transition(kind,id,payload={}){requireWrite();const {error}=await supabase.rpc('biblioteca_transition',{p_action:kind,p_book:id,p_data:payload});if(error)throw error;}
async function action(a,el){const id=Number(el.dataset.id),b=s.book(id);if(a==='close'){modal.close();return;}if(a==='view'){s.view=el.dataset.view;s.personHistory=null;s.page=1;render();return;}if(a==='book'){bookDetail(id);return;}if(a==='duplicates'||a==='recommend'){s.view=a==='duplicates'?'duplicados':'recomendador';s.personHistory=null;render();return;}if(a==='person-history'){s.personHistory=el.dataset.person;render();return;}if(a==='apply-filters'){for(const [key,node] of Object.entries({q:'catalog-q',genero:'filter-genero',codigo_p:'filter-codigo',idioma:'filter-idioma',estado_lectura:'filter-estado'}))s.filters[key]=document.getElementById(node).value;s.page=1;render();return;}if(a==='clear-filters'){s.filters={q:'',genero:'',codigo_p:'',idioma:'',estado_lectura:'',favorito:false};s.page=1;render();return;}if(a==='toggle-favorites'){s.filters.favorito=!s.filters.favorito;render();return;}if(a==='toggle-view-mode'){s.viewMode=s.viewMode==='lista'?'cuadricula':'lista';render();return;}if(a==='page'){s.page=Number(el.dataset.page);render();return;}if(a==='review-filter'){s.reviewKey=el.dataset.key;render();return;}
 if(a.startsWith('label-')){const visible=s.labelFilteredBooks();if(a==='label-apply'){for(const [k,node] of Object.entries({q:'label-q',codigo_p:'label-owner',genero:'label-genre',dewey:'label-dewey'}))s.labelFilters[k]=document.getElementById(node).value;}if(a==='label-select-visible')visible.forEach(b=>s.selectedLabels.add(b.id));if(a==='label-unselect-visible')visible.forEach(b=>s.selectedLabels.delete(b.id));if(a==='label-select-all')s.data.books.filter(b=>!b.eliminado&&b.lista==='catalogo').forEach(b=>s.selectedLabels.add(b.id));if(a==='label-clear')s.selectedLabels.clear();render();return;}
 if(a==='print-labels'){const books=s.data.books.filter(b=>s.selectedLabels.has(b.id));if(!books.length)throw new Error('Seleccioná al menos un libro.');const {jsPDF}=await import('jspdf');const pdf=new jsPDF();books.forEach((b,i)=>{if(i&&i%60===0)pdf.addPage();const n=i%60,x=10+(n%6)*32,y=10+Math.floor(n/6)*27;pdf.rect(x,y,30,25);pdf.setFontSize(10);pdf.text([u.deweyFmt(b.dewey)||'SIN',u.cutterAuthor(b.autor),`${b.codigo_p||''}-${b.item||''}`],x+15,y+7,{align:'center',maxWidth:28});});pdf.save('etiquetas.pdf');return;}
 if(a==='export-json'){u.downloadBlob(`biblioteca-${u.today()}.json`,JSON.stringify({version:18,...s.data},null,2),'application/json');return;}if(a==='export-csv'){u.downloadBlob('biblioteca.csv',u.csvText(s.data.books,Object.keys(s.data.books[0]||{titulo:''})),'text/csv');return;}if(a==='download-backup'){const backup=await latestBackup();if(!backup)throw new Error('Todavía no hay respaldos. Podés exportar JSON ahora.');u.downloadBlob(backup.name,backup.blob);return;}
 requireWrite();
 if(a==='new-book'||a==='edit-book'){editBook(a==='edit-book'?id:null,{...(el.dataset.list?{lista:el.dataset.list}:{})});return;}
 if(a==='isbn'){dialog('Buscar por ISBN',field('isbn','ISBN','','text','required')+button('Escanear con cámara','scan-isbn'),async f=>{const result=await u.lookupIsbn(f.get('isbn'));setTimeout(()=>editBook(null,result),0);});return;}
 if(a==='scan-isbn'){const {BrowserMultiFormatReader}=await import('@zxing/browser');const reader=new BrowserMultiFormatReader();const video=document.createElement('video');video.style.maxWidth='100%';modal.append(video);let controls;const stop=()=>{controls?.stop();video.remove();};modal.addEventListener('close',stop,{once:true});controls=await reader.decodeFromVideoDevice(undefined,video,(result)=>{if(result){const input=modal.querySelector('[name=isbn]');if(input)input.value=u.cleanIsbn(result.getText());stop();}});return;}
 if(a==='start-reading'){selectBook('Empezar una lectura',id=>transition('start',id));return;}if(a==='add-next'){selectBook('Agregar a próximas lecturas',id=>data.updateBook(id,{proxima_lectura:true}));return;}
 if(a==='update-page'){dialog('Actualizar página',field('page','Página actual',b.pagina_actual||0,'number',`required min="0" ${b.paginas?'max="'+b.paginas+'"':''}`),f=>transition('page',id,{page:Number(f.get('page'))}));return;}
 if(a==='finish-reading'){dialog('Concluir lectura',text('comment','Comentario'),f=>transition('finish',id,{comment:f.get('comment')}));return;}
 if(a==='abandon-reading'){dialog('Abandonar lectura','<p>El historial anterior se conserva.</p>',()=>transition('abandon',id));return;}
 if(a==='cover'){dialog('Subir portada',field('image','Imagen','','file','accept="image/jpeg,image/png,image/webp" required'),f=>data.uploadCover(id,f.get('image')));return;}
 if(a==='phone-cover'){const url=new URL(location.href);url.searchParams.set('cover',id);const {default:QR}=await import('qrcode');const qr=await QR.toDataURL(url.href);dialog('Cargar desde el celular',`<p>Abrí este enlace en tu celular e iniciá sesión con una cuenta autorizada. El permiso se verifica antes de aceptar la imagen.</p><img src="${qr}" alt="Código QR del libro"><p><a href="${u.esc(url.href)}">Abrir carga de portada</a></p>`);return;}
 if(a==='internet'){toast('Buscando datos…');const options=await u.internetOptions(b.titulo,b.autor);dialog('Elegí la información',options.map((o,i)=>`<section class="lib-panel"><h3>${u.esc(o.titulo)}</h3><p>${u.esc(o.autor)} · ${u.esc(o.fuente)}</p><p>${u.esc(o.descripcion)}</p>${o.portada_url?`<img src="${u.esc(o.portada_url)}" alt="Portada propuesta" style="max-width:100px">`:''}${button('Completar campos vacíos','apply-option',i)}</section>`).join('')||'<p>No se encontraron resultados.</p>');modal.options=options;modal.bookId=id;return;}
 if(a==='apply-option'){const option=modal.options[id],book=s.book(modal.bookId),patch={};for(const k of ['titulo','autor','editorial','paginas','isbn','idioma','descripcion'])if(!book[k]&&option[k])patch[k]=option[k];if(!book.portada&&option.portada_url)patch.portada=option.portada_url;await data.updateBook(book.id,patch);}
 else if(a==='new-loan'){dialog('Registrar préstamo',`<label class="lib-field">Libro<select name="book" class="lib-select">${s.data.books.filter(b=>!b.eliminado&&b.lista==='catalogo'&&!s.data.loans.some(l=>l.libro_id===b.id&&l.activo)).map(b=>`<option value="${b.id}">${u.esc(b.titulo)}</option>`).join('')}</select></label>`+field('person','Persona','','text','required')+field('due','Devolución prevista','','date')+text('notes','Notas'),f=>transition('loan',Number(f.get('book')),{person:f.get('person'),due:f.get('due')||null,notes:f.get('notes')}));return;}
 else if(a==='return-loan'||a==='lost-loan'){const loan=s.data.loans.find(l=>l.id===id);dialog(a==='return-loan'?'Registrar devolución':'Marcar perdido',text('condition','Estado / observaciones'),f=>transition(a==='return-loan'?'return':'lost',loan.libro_id,{loan:id,condition:f.get('condition')}));return;}
 else if(a==='delete-loan'||a==='delete-forever'||a==='empty-trash'){dialog('Confirmar eliminación definitiva','<p>Esta acción no se puede deshacer. Exportá una copia si querés conservar el historial.</p>',async()=>{if(a==='delete-loan')await data.deleteLoan(id);else if(a==='delete-forever')await data.deleteBookForever(id);else for(const book of s.data.books.filter(b=>b.eliminado))await data.deleteBookForever(book.id);});return;}
 else if(a==='start-book')await transition('start',id);
 else if(a==='favorite')await data.updateBook(id,{favorito:!b.favorito});
 else if(a==='add-next-book'||a==='remove-next')await data.updateBook(id,{proxima_lectura:a==='add-next-book'});
 else if(a==='buy-book')await data.updateBook(id,{lista:'catalogo',fecha_agregado:u.today()});
 else if(a==='trash-book')await data.deleteBookSoft(id);
 else if(a==='restore-book')await data.restoreBook(id);
 else if(a==='remove-cover')await data.updateBook(id,{portada:null});
 else throw new Error('No se pudo identificar la acción.');
 modal.close();await reload();toast('Guardado.');
}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;e.preventDefault();el.disabled=true;try{await action(el.dataset.action,el);}catch(error){toast(error.message);}finally{el.disabled=false;}});
document.addEventListener('change',e=>{if(e.target.dataset.labelId){const id=Number(e.target.dataset.labelId);e.target.checked?s.selectedLabels.add(id):s.selectedLabels.delete(id);render();}});
try{const access=await sessionAndAccess();if(!access.user){root.innerHTML='<main class="lib-main"><h1>Tu biblioteca privada</h1><p>Iniciá sesión en Habits para continuar.</p><a href="./">Ir a Habits</a></main>';}else if(!access.allowed){root.innerHTML='<main class="lib-main"><h1>Biblioteca con acceso restringido</h1><p>Esta cuenta no está autorizada. Tus hábitos, diario y calendario siguen disponibles.</p><a href="./">Volver a Habits</a></main>';}else{s.user=access.user;await ensureConfig();await reload();s.viewMode=s.config.vista_default||'cuadricula';render();if(canWrite)createDailyBackup(s.data).catch(()=>toast('No se pudo crear el respaldo diario. Podés exportar JSON desde Configuración.'));const bookId=Number(new URL(location.href).searchParams.get('cover'));if(bookId&&s.book(bookId)&&canWrite)await action('cover',{dataset:{id:bookId}});}}catch(error){root.innerHTML=`<main class="lib-main"><h1>No se pudo abrir la biblioteca</h1><p>${u.esc(error.message)}</p><p>Revisá la conexión y que las migraciones de Biblioteca estén aplicadas.</p><a href="./">Volver a Habits</a></main>`;}
supabase.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'){s.data={books:[],loans:[],readings:[],finished:[],people:[],config:[]};s.covers.clear();modal.close();root.innerHTML='<main class="lib-main"><p>Sesión cerrada.</p><a href="./">Volver a Habits</a></main>';}});
