import * as db from './store.js';
import {dayKey,addDays,weekKeys,occurs,eventOnDate,flexibleWeekly,weeklyProgress,effectiveHabitsForDate,dayStats} from './domain.js';
import {daySummary} from './daily.js';
import {catalog} from './library-bridge.js';
import {activeWorkBlock} from './work-context.js';
import {effectiveDayMode} from './planning.js';
export function validateBackup(value){
 if(!value||value.version!==1||!value.records||Array.isArray(value.records)||typeof value.records!=='object')throw new Error('Este archivo no es un respaldo válido de Habits.');
 const allowed=new Set(['settings','area','habit','log','event','eventLog','task','project','book','reading','quote','journal','timer','word','dailyPlan','photo']);
 const records=Object.entries(value.records);if(records.length>30000)throw new Error('El respaldo supera los 30.000 registros.');
 for(const [id,r] of records)if(!id||id.length>200||['__proto__','constructor','prototype'].includes(id)||!r||r.id!==id||!allowed.has(r.kind)||!r.data||typeof r.data!=='object'||Array.isArray(r.data))throw new Error('El respaldo contiene registros inválidos.');
 return records.map(([,r])=>r).filter(r=>!r.deleted);
}
export function extrasView({btn}){return `<section class="panel"><h2>Un momento para vos</h2><div class="button-row">${btn('¿Qué sigue?','extra-next','','button outline')}${btn('Tengo un rato libre','extra-free','','button outline')}${btn('Cerrar mi día','extra-close','','button outline')}${btn('Clima de Asunción','extra-weather','','button outline')}</div></section>`;}
export async function extrasAction(a,el,{showModal,input,btn,esc,modal,toast}){
 if(!a.startsWith('extra-'))return false;const today=dayKey(),now=new Date(),clock=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`;
 const ev=d=>db.records('event').filter(e=>occurs(e,d)).map(e=>eventOnDate(e,d)).sort((a,b)=>(a.time||'').localeCompare(b.time||''));
 if(a==='extra-next'){const events=ev(today).filter(e=>e.time>=clock&&!db.records('eventLog').some(l=>l.eventId===e.id&&l.date===today));showModal('¿Qué sigue?',events.length?events.map(e=>`<p><strong>${esc(e.time)}</strong> · ${esc(e.name)}</p>`).join(''):'<p>No tenés más eventos con hora pendientes para hoy.</p>');}
 if(a==='extra-free')showModal('Tengo un rato libre',`<form>${input('¿Cuántos minutos tenés?','minutes',15,'number','min="1" max="240" required')}<button class="button primary" type="submit">Ver ideas</button></form>`,f=>{const minutes=Number(f.get('minutes')),logs=db.records('log'),events=db.records('event'),working=!!activeWorkBlock(events,today,clock);const suggestions=effectiveHabitsForDate(db.records('habit'),today,effectiveDayMode(db.records('settings')[0]||{},today)).filter(h=>!logs.some(l=>l.habitId===h.id&&l.date===today&&['done','skip'].includes(l.status))&&(!flexibleWeekly(h)||!weeklyProgress(h,logs,today).complete)&&(h.type!=='time'||h.target<=minutes)&&(!working||h.area==='trabajo'||h.essential));showModal('A tu ritmo',suggestions.map(h=>`<p>${esc(h.name)} ${h.type==='time'?`· ${h.target} min`:flexibleWeekly(h)?`· ${weeklyProgress(h,logs,today).done}/${weeklyProgress(h,logs,today).target} esta semana`:''}</p>`).join('')||'<p>No tenés una actividad pendiente que encaje ahora. También podés descansar.</p>');});
 if(a==='extra-close'){const summary=daySummary({habits:db.records('habit'),logs:db.records('log'),events:db.records('event'),eventLogs:db.records('eventLog'),readings:db.records('reading'),journals:db.records('journal')},today,effectiveDayMode(db.records('settings')[0]||{},today));showModal('Tu cierre del día',`<p>${esc(summary)}</p><h3>Mañana</h3>${ev(addDays(today,1)).map(e=>`<p>${esc(e.time||'Todo el día')} · ${esc(e.name)}</p>`).join('')||'<p>Sin eventos programados.</p>'}${btn('Escribir cómo me sentí','journal','','button primary')}`);}
 if(a==='extra-week'){const week=weekKeys(today),allLogs=db.records('log'),doneCount=week.map(d=>dayStats(db.records('habit'),allLogs,d,effectiveDayMode(db.records('settings')[0]||{},d))).reduce((n,s)=>n+s.done,0),reads=db.records('reading').filter(r=>week.includes(r.date)),c=catalog(),booksFinished=c.allowed?(c.finishedCount||0):db.records('book').filter(b=>b.status==='finished').length;const medals=[];if(db.records('log').some(l=>l.status==='done'))medals.push('🌱 Tu primer paso');if(db.records('log').filter(l=>l.status==='done').length>=30)medals.push('🏅 30 hábitos completados');if(booksFinished>=10)medals.push('📚 10 libros terminados');showModal('Tu semana y tus logros',`<p>Esta semana registraste <strong>${doneCount} hábitos</strong> y <strong>${reads.reduce((n,r)=>n+Number(r.minutes),0)} minutos de lectura</strong>.</p><p>¡Bien por el tiempo que te dedicaste!</p>${medals.map(m=>`<p>${m}</p>`).join('')}`);}
 if(a==='extra-weather'){showModal('Clima de Asunción','<p>Consultando el clima…</p>');try{const res=await fetch('https://api.open-meteo.com/v1/forecast?latitude=-25.2865&longitude=-57.647&current=temperature_2m,apparent_temperature&timezone=America%2FAsuncion');if(!res.ok)throw new Error();const {current}=await res.json();showModal('Clima de Asunción',`<p><strong>${Number(current.temperature_2m)} °C</strong> · Sensación térmica ${Number(current.apparent_temperature)} °C</p><p>Actualizado: ${esc(current.time.replace('T',' '))} · Asunción</p><a href="https://open-meteo.com/" target="_blank" rel="noopener">Datos meteorológicos: Open-Meteo</a>`);}catch{showModal('Clima de Asunción','<p>No se pudo consultar el clima. Probá de nuevo cuando tengas conexión.</p>');}}
 if(a==='extra-import')showModal('Importar respaldo',`<p>Se agregarán solamente registros que todavía no estén en esta cuenta. Los existentes se conservan.</p><form>${input('Respaldo JSON','backup','','file','accept="application/json,.json" required')}<button class="button primary" type="submit">Revisar archivo</button></form>`,async f=>{const file=f.get('backup');if(file.size>20971520)throw new Error('El archivo supera los 20 MB.');const records=validateBackup(JSON.parse(await file.text())),missing=records.filter(r=>!db.raw(r.id)&&!r.data.workoutPhoto&&r.kind!=='photo'),existing=records.length-missing.length;showModal('Revisar importación',`<p>Se agregarán ${missing.length} registros. Se conservarán o excluirán ${existing} registros existentes o referencias a fotos privadas.</p><form><button class="button primary" type="submit">Importar ${missing.length} registros</button></form>`,()=>{for(const r of missing)db.put(r.kind,r.data,r.id);modal.close();toast('Respaldo importado.');});});
 return true;
}
