import * as db from './store.js';
import {dayKey,weekKeys,parseDay} from './domain.js';
import {subjects as subjectRecords,englishPractice as englishPracticeRecords} from './selectors.js';
import {eventConflictDates,conflictMessage} from './scheduling.js';
const SKILLS={listening:'Comprensión auditiva',reading:'Lectura',speaking:'Conversación',writing:'Escritura'};
export function planningView({esc,btn}){
 const subjects=subjectRecords(db.records('project')),tasks=db.records('task').filter(t=>t.area==='facultad'),practice=englishPracticeRecords(db.records('journal')),week=weekKeys(dayKey());
 return `<section class="panel"><h2>Facultad</h2>${btn('Agregar materia','plan-subject','','button outline')}${subjects.map(p=>{const grades=(p.grades||[]),average=grades.length?grades.reduce((n,g)=>n+g.value,0)/grades.length:null;return `<article><h3>${esc(p.name)}</h3><p>${esc(p.semester||'Sin semestre')} · Aula ${esc(p.room||'sin definir')}</p><p>${average===null?'Sin notas registradas':`Promedio simple: ${average.toFixed(2)}`}</p>${btn('Editar materia y notas','plan-subject',`data-id="${esc(p.id)}"`,'text-button')}${btn('Agregar examen o entrega','plan-assignment',`data-id="${esc(p.id)}"`,'text-button')}</article>`;}).join('')||'<p class="muted">Todavía no cargaste materias.</p>'}<h3>Próximas entregas y exámenes</h3>${tasks.filter(t=>!t.done).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')).map(t=>`<p>${esc(t.name)} · ${t.due?`${Math.ceil((parseDay(t.due)-parseDay(dayKey()))/86400000)} días`:'Sin fecha'} ${btn('Ver / editar','edit-task',`data-id="${esc(t.id)}"`,'text-button')}</p>`).join('')||'<p>Sin pendientes.</p>'}</section><section class="panel"><h2>Trabajo y clases</h2><p>Cargá un bloque semanal para tu trabajo, facultad o inglés.</p>${btn('Crear horario semanal','plan-schedule','','button outline')}</section><section class="panel"><h2>Mi inglés</h2>${btn('Registrar práctica','plan-english','','button outline')}<div class="stat-grid english-skills">${Object.entries(SKILLS).map(([skill,label])=>`<div><h3>${label}</h3><p>${practice.filter(p=>p.skill===skill&&week.includes(p.date)).reduce((n,p)=>n+p.minutes,0)} minutos esta semana</p></div>`).join('')}</div></section><section class="panel"><h2>Mis tipos de día</h2><p>Elegí cómo empieza cada día de la semana. Trabajo y Facultad priorizan su área; Fin de semana oculta la rutina laboral; Tranquilo y Descanso muestran solo lo esencial.</p>${btn('Organizar mi semana','plan-week','','button outline')}</section>`;
}
export async function planningAction(a,el,{showModal,input,textarea,select,modal,toast}){
 if(!a.startsWith('plan-'))return false;
 const projects=db.records('project'),settings=db.records('settings')[0]||{};
 const save=(kind,v,id)=>{db.put(kind,v,id);modal.close();toast('Guardado.');};
 if(a==='plan-subject'){const p=projects.find(p=>p.id===el.dataset.id)||{};showModal('Materia',`<form>${input('Materia','name',p.name,'text','required')}${input('Semestre','semester',p.semester)}${input('Aula','room',p.room)}${textarea('Notas numéricas, separadas por coma','grades',(p.grades||[]).map(g=>g.value).join(', '))}<p class="muted small">Usá la misma escala para todas las notas. El promedio es simple, sin ponderaciones.</p><button class="button primary" type="submit">Guardar</button></form>`,f=>{const values=String(f.get('grades')).trim(),grades=values?values.split(',').map(x=>({value:Number(x.trim())})):[];if(grades.some(g=>!Number.isFinite(g.value)||g.value<0))throw new Error('Revisá las notas.');save('project',{...p,...Object.fromEntries(f),category:'subject',area:'facultad',grades},p.id);});}
 if(a==='plan-assignment')showModal('Examen o entrega',`<form>${select('Tipo','category',[['exam','Examen'],['assignment','Entrega']],'exam')}${input('Título','name','','text','required')}${input('Fecha','due',dayKey(),'date','required')}${textarea('Temas y detalles','note')}<button class="button primary" type="submit">Guardar</button></form>`,f=>save('task',{...Object.fromEntries(f),projectId:el.dataset.id,area:'facultad',done:false,priority:'alta'}));
 if(a==='plan-schedule')showModal('Horario semanal',`<form>${input('Nombre','name','','text','required')}${select('Área','area',[['trabajo','Trabajo'],['facultad','Facultad'],['ingles','Inglés']],'trabajo')}${input('Primera fecha','date',dayKey(),'date','required')}${input('Hora inicial','time','08:00','time','required')}${input('Hora final','end','09:00','time','required')}${input('Hasta (fin de semestre, opcional)','until','','date')}${input('Aula o lugar','location')}<button class="button primary" type="submit">Guardar</button></form>`,f=>{const v={...Object.fromEntries(f),repeat:'weekly'};if(v.end<=v.time)throw new Error('La hora final debe ser posterior a la inicial.');if(v.until&&v.until<v.date)throw new Error('Revisá la fecha final.');const conflicts=eventConflictDates(v,db.records('event'));if(conflicts.length&&!confirm(conflictMessage(conflicts,d=>parseDay(d).toLocaleDateString('es-PY',{day:'numeric',month:'short'}))+' ¿Guardar igual?'))return;save('event',v);});
 if(a==='plan-english')showModal('Práctica de inglés',`<form>${select('Habilidad','skill',Object.entries(SKILLS),'listening')}${input('Fecha','date',dayKey(),'date','required')}${input('Minutos','minutes',15,'number','required min="1" max="1440"')}${textarea('Qué practicaste','text')}<button class="button primary" type="submit">Guardar</button></form>`,f=>save('journal',{...Object.fromEntries(f),englishPractice:true,minutes:Number(f.get('minutes')),at:new Date().toISOString()}));
 if(a==='plan-week')showModal('Tu semana',`<form>${['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'].map((day,i)=>select(day,'day'+i,[['habitual','Habitual'],['trabajo','Día de trabajo'],['facultad','Día de facu'],['finDeSemana','Fin de semana'],['tranquilo','Tranquilo'],['descanso','Descanso']],settings.weekModes?.[i]||'habitual')).join('')}<button class="button primary" type="submit">Guardar</button></form>`,f=>save('settings',{...settings,weekModes:Object.fromEntries(Array.from({length:7},(_,i)=>[i,f.get('day'+i)]))},'settings'));
 return true;
}
export function effectiveDayMode(settings,date=dayKey()) {return settings.dayModes?.[date]||settings.dayModeDate===date&&settings.dayMode||settings.weekModes?.[parseDay(date).getDay()]||'habitual';}
