-- Biblioteca v18 privada dentro del mismo proyecto Supabase de Habits.
-- Habits sigue siendo multiusuario. La biblioteca avanzada queda habilitada
-- para exactamente UNA cuenta, sin hardcodear su UUID en el frontend.

create table if not exists public.biblioteca_access (
  slot smallint primary key default 1 check (slot = 1),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.biblioteca_access enable row level security;
revoke all on public.biblioteca_access from anon, authenticated;
grant select on public.biblioteca_access to authenticated;

drop policy if exists biblioteca_access_self on public.biblioteca_access;
create policy biblioteca_access_self
on public.biblioteca_access
for select
to authenticated
using (user_id = (select auth.uid()));

create or replace function public.has_biblioteca_access()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.biblioteca_access
    where slot = 1 and user_id = auth.uid()
  );
$$;

revoke all on function public.has_biblioteca_access() from public, anon;
grant execute on function public.has_biblioteca_access() to authenticated;

create table if not exists public.biblioteca_libros (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  legacy_id bigint,
  item integer,
  codigo_p text,
  dewey text,
  dewey_orden numeric,
  titulo text not null,
  autor text,
  genero text,
  subdivision text,
  editorial text,
  paginas integer,
  observaciones text,
  isbn text,
  idioma text default 'Español',
  portada text,
  descripcion text,
  dedicatoria text,
  rating integer,
  estado_lectura text default 'no_leido',
  pagina_actual integer,
  lista text default 'catalogo',
  relacionados text,
  fecha_agregado date,
  fecha_inicio date,
  fecha_fin date,
  autografiado boolean not null default false,
  favorito boolean not null default false,
  proxima_lectura boolean not null default false,
  eliminado boolean not null default false,
  fecha_eliminado timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint biblioteca_libros_rating check (rating is null or rating between 0 and 5),
  constraint biblioteca_libros_paginas check (paginas is null or paginas >= 0),
  constraint biblioteca_libros_pagina_actual check (pagina_actual is null or pagina_actual >= 0),
  unique(owner_id, legacy_id)
);

create table if not exists public.biblioteca_lecturas (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  legacy_id bigint,
  libro_id bigint not null references public.biblioteca_libros(id) on delete cascade,
  fecha date not null,
  pagina integer,
  paginas_leidas integer not null default 0,
  created_at timestamptz not null default now(),
  unique(owner_id, legacy_id)
);

create table if not exists public.biblioteca_lecturas_finalizadas (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  legacy_id bigint,
  libro_id bigint not null references public.biblioteca_libros(id) on delete cascade,
  fecha_inicio date,
  fecha_fin date not null,
  tiempo_lectura text,
  dias_lectura numeric,
  comentario text,
  created_at timestamptz not null default now(),
  unique(owner_id, legacy_id)
);

create table if not exists public.biblioteca_personas (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  legacy_id bigint,
  nombre text not null,
  telefono text,
  notas text,
  fecha_creado timestamptz,
  created_at timestamptz not null default now(),
  unique(owner_id, legacy_id),
  unique(owner_id, nombre)
);

create table if not exists public.biblioteca_prestamos (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  legacy_id bigint,
  libro_id bigint not null references public.biblioteca_libros(id) on delete cascade,
  persona text not null,
  persona_id bigint references public.biblioteca_personas(id) on delete set null,
  fecha_prestamo date not null,
  fecha_devolucion_prevista date,
  fecha_devuelto date,
  notas text,
  activo boolean not null default true,
  estado text default 'prestado',
  estado_devolucion text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(owner_id, legacy_id)
);

create table if not exists public.biblioteca_config (
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  clave text not null,
  valor text,
  updated_at timestamptz not null default now(),
  primary key(owner_id, clave)
);

create index if not exists biblioteca_libros_owner_idx on public.biblioteca_libros(owner_id);
create index if not exists biblioteca_libros_catalogo_idx on public.biblioteca_libros(owner_id, lista, eliminado);
create index if not exists biblioteca_libros_titulo_idx on public.biblioteca_libros(owner_id, titulo);
create index if not exists biblioteca_libros_autor_idx on public.biblioteca_libros(owner_id, autor);
create index if not exists biblioteca_libros_dewey_idx on public.biblioteca_libros(owner_id, dewey_orden);
create index if not exists biblioteca_libros_codigo_idx on public.biblioteca_libros(owner_id, codigo_p, item);
create index if not exists biblioteca_lecturas_libro_idx on public.biblioteca_lecturas(owner_id, libro_id, fecha desc);
create index if not exists biblioteca_finalizadas_libro_idx on public.biblioteca_lecturas_finalizadas(owner_id, libro_id, fecha_fin desc);
create index if not exists biblioteca_prestamos_libro_idx on public.biblioteca_prestamos(owner_id, libro_id);
create index if not exists biblioteca_prestamos_activo_idx on public.biblioteca_prestamos(owner_id, activo);

alter table public.biblioteca_libros enable row level security;
alter table public.biblioteca_lecturas enable row level security;
alter table public.biblioteca_lecturas_finalizadas enable row level security;
alter table public.biblioteca_personas enable row level security;
alter table public.biblioteca_prestamos enable row level security;
alter table public.biblioteca_config enable row level security;

revoke all on public.biblioteca_libros from anon;
revoke all on public.biblioteca_lecturas from anon;
revoke all on public.biblioteca_lecturas_finalizadas from anon;
revoke all on public.biblioteca_personas from anon;
revoke all on public.biblioteca_prestamos from anon;
revoke all on public.biblioteca_config from anon;

grant select, insert, update, delete on public.biblioteca_libros to authenticated;
grant select, insert, update, delete on public.biblioteca_lecturas to authenticated;
grant select, insert, update, delete on public.biblioteca_lecturas_finalizadas to authenticated;
grant select, insert, update, delete on public.biblioteca_personas to authenticated;
grant select, insert, update, delete on public.biblioteca_prestamos to authenticated;
grant select, insert, update, delete on public.biblioteca_config to authenticated;

do $$
declare t text;
begin
  foreach t in array array[
    'biblioteca_libros',
    'biblioteca_lecturas',
    'biblioteca_lecturas_finalizadas',
    'biblioteca_personas',
    'biblioteca_prestamos',
    'biblioteca_config'
  ] loop
    execute format('drop policy if exists %I on public.%I', t || '_private', t);
    execute format(
      'create policy %I on public.%I for all to authenticated using (owner_id = (select auth.uid()) and public.has_biblioteca_access()) with check (owner_id = (select auth.uid()) and public.has_biblioteca_access())',
      t || '_private', t
    );
  end loop;
end $$;

create or replace function public.biblioteca_touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists biblioteca_libros_touch on public.biblioteca_libros;
create trigger biblioteca_libros_touch before update on public.biblioteca_libros
for each row execute function public.biblioteca_touch_updated_at();

drop trigger if exists biblioteca_prestamos_touch on public.biblioteca_prestamos;
create trigger biblioteca_prestamos_touch before update on public.biblioteca_prestamos
for each row execute function public.biblioteca_touch_updated_at();

drop trigger if exists biblioteca_config_touch on public.biblioteca_config;
create trigger biblioteca_config_touch before update on public.biblioteca_config
for each row execute function public.biblioteca_touch_updated_at();

-- Bucket privado para portadas. Cada archivo se guarda bajo <auth.uid()>/...
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'biblioteca-portadas',
  'biblioteca-portadas',
  false,
  10485760,
  array['image/jpeg','image/png','image/webp','image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists biblioteca_portadas_select on storage.objects;
create policy biblioteca_portadas_select on storage.objects
for select to authenticated
using (
  bucket_id = 'biblioteca-portadas'
  and public.has_biblioteca_access()
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists biblioteca_portadas_insert on storage.objects;
create policy biblioteca_portadas_insert on storage.objects
for insert to authenticated
with check (
  bucket_id = 'biblioteca-portadas'
  and public.has_biblioteca_access()
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists biblioteca_portadas_update on storage.objects;
create policy biblioteca_portadas_update on storage.objects
for update to authenticated
using (
  bucket_id = 'biblioteca-portadas'
  and public.has_biblioteca_access()
  and (storage.foldername(name))[1] = (select auth.uid())::text
)
with check (
  bucket_id = 'biblioteca-portadas'
  and public.has_biblioteca_access()
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists biblioteca_portadas_delete on storage.objects;
create policy biblioteca_portadas_delete on storage.objects
for delete to authenticated
using (
  bucket_id = 'biblioteca-portadas'
  and public.has_biblioteca_access()
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

-- Configuración visual por defecto equivalente a la app Flask.
-- Se crea cuando la cuenta autorizada abra la biblioteca por primera vez.
create or replace function public.biblioteca_asegurar_config()
returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
  if not public.has_biblioteca_access() then
    raise exception 'Biblioteca privada no habilitada para esta cuenta';
  end if;
  insert into public.biblioteca_config(owner_id, clave, valor)
  values
    (auth.uid(), 'nombre_biblioteca', 'Mi biblioteca'),
    (auth.uid(), 'color_principal', '#6f7f64'),
    (auth.uid(), 'color_fondo', '#f5f1e8'),
    (auth.uid(), 'color_texto', '#292823'),
    (auth.uid(), 'color_tarjeta', '#fffdf8'),
    (auth.uid(), 'fuente', 'Georgia, serif'),
    (auth.uid(), 'fuente_titulos', 'Georgia, serif'),
    (auth.uid(), 'fuente_botones', 'Georgia, serif'),
    (auth.uid(), 'tamano_texto', '16'),
    (auth.uid(), 'tamano_titulos', '30'),
    (auth.uid(), 'tamano_botones', '16'),
    (auth.uid(), 'por_pagina', '200'),
    (auth.uid(), 'mostrar_favoritos_catalogo', '1'),
    (auth.uid(), 'vista_default', 'cuadricula')
  on conflict (owner_id, clave) do nothing;
end;
$$;

revoke all on function public.biblioteca_asegurar_config() from public, anon;
grant execute on function public.biblioteca_asegurar_config() to authenticated;

-- Activación administrativa (ejecutar UNA vez, sustituyendo el UUID):
-- insert into public.biblioteca_access(slot, user_id)
-- values (1, 'UUID-DE-LA-CUENTA')
-- on conflict (slot) do update set user_id = excluded.user_id;
